// Norwegian standard chart of accounts (Standard kontoplan / NS 4102), sourced
// directly from a real Tripletex "Kontoplan" export (code, name, Kontotype,
// Saldogruppe, SAF-T-kode versjon 1.3, and Mva-kode columns) rather than
// hand-translated into English — every name below is the genuine Norwegian
// account name. A handful of rows unique to that specific export's own company
// (intercompany balances named after real counterparty companies, e.g.
// "Mellomværende <Company> AS") were left out — those aren't generic accounts
// any new company should start with. defaultVatCode/defaultVatPct are set only
// where the source's Mva-kode is one this app's own VAT code list (MVA_CODES in
// utils.js) already knows how to handle; three accounts in the source use an
// import-VAT code (14/15/21) the app doesn't support yet — see the comment near
// each of the three below.
const DEFAULT_ACCOUNTS=[
  // 10 Immaterielle eiendeler o.l.
  {code:"1000",name:"Forskning og utvikling, ervervet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1000"},
  {code:"1005",name:"Forskning og utvikling, egenutviklet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1000"},
  {code:"1020",name:"Konsesjoner, ervervet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1025",name:"Konsesjoner, egenutviklet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1030",name:"Patenter, ervervet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1035",name:"Patenter, egenutviklet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1040",name:"Lisenser, ervervet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1045",name:"Lisenser, egenutviklet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1050",name:"Varemerker, ervervet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1055",name:"Varemerker, egenutviklet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1060",name:"Andre rettigheter, ervervet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1065",name:"Andre rettigherer, egenutviklet",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1020"},
  {code:"1070",name:"Utsatt skattefordel",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1070"},
  {code:"1080",name:"Goodwill, ervervet",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe B: Ervervet forretningsverdi",saftCode13:"1080"},
  // 11 Tomter, bygninger og annen fast eiendom
  {code:"1100",name:"Forretningsbygg",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe I: Forretningsbygg",saftCode13:"1105"},
  {code:"1117",name:"Elektroteknisk utrustning i kraftforetak",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe G: Anlegg for overføring og distribusjon av elektrisk kraft mv.",saftCode13:"1117"},
  {code:"1120",name:"Bygningsmessig anlegg",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe H: Bygg og anlegg mv.",saftCode13:"1120"},
  {code:"1130",name:"Anlegg under utførelse",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1130"},
  {code:"1140",name:"Jordbrukseiendommer",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1140"},
  {code:"1145",name:"Skogbrukseiendommer",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1150"},
  {code:"1150",name:"Tomter",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1150"},
  {code:"1155",name:"Andre grunnarealer",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1150"},
  {code:"1160",name:"Boliger inkl. tomter",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1160"},
  {code:"1180",name:"Investeringseiendommer",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe J: Fast teknisk installasjon i bygninger",saftCode13:"1180"},
  {code:"1190",name:"Andre anleggsmidler",accountType:"Balanse - eiendeler",balanceGroup:"Driftsmiddel som avskrives lineært",saftCode13:"1290"},
  // 12 Transportmidler, inventar, maskiner o.l.
  {code:"1200",name:"Maskiner og anlegg",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv.",saftCode13:"1205",defaultVatCode:"1",defaultVatPct:25},
  {code:"1210",name:"Maskiner og anlegg under utførelse",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1130",defaultVatCode:"1",defaultVatPct:25},
  {code:"1220",name:"Skip",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe E: Skip, fartøyer mv.",saftCode13:"1221",defaultVatCode:"1",defaultVatPct:25},
  {code:"1224",name:"Rigger",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe E: Skip, fartøyer mv.",saftCode13:"1221",defaultVatCode:"1",defaultVatPct:25},
  {code:"1225",name:"Fly",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe F: Fly og helikopter",saftCode13:"1225",defaultVatCode:"1",defaultVatPct:25},
  {code:"1230",name:"Personbiler/stasjonsvogner",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe C: Vogntog, lastebiler mv.",saftCode13:"1238",defaultVatCode:"1",defaultVatPct:25},
  {code:"1233",name:"Varebiler",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe C: Vogntog, lastebiler mv.",saftCode13:"1238",defaultVatCode:"1",defaultVatPct:25},
  {code:"1242",name:"Lastebiler",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv.",saftCode13:"1238"},
  {code:"1243",name:"Traktorer",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv.",saftCode13:"1205"},
  {code:"1248",name:"Trucker",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv.",saftCode13:"1205",defaultVatCode:"1",defaultVatPct:25},
  {code:"1250",name:"Inventar",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv.",saftCode13:"1205",defaultVatCode:"1",defaultVatPct:25},
  {code:"1251",name:"Avskrivning kto. 1250 - Inventar",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv.",saftCode13:"1205"},
  {code:"1260",name:"Fast bygningsinventar, eget bygg",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv.",saftCode13:"1205",defaultVatCode:"1",defaultVatPct:25},
  {code:"1265",name:"Fast bygningsinventar, leide bygg",accountType:"Balanse - eiendeler",balanceGroup:"Driftsmiddel som avskrives lineært",saftCode13:"1290",defaultVatCode:"1",defaultVatPct:25},
  {code:"1270",name:"Verktøy o.l.",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv.",saftCode13:"1205",defaultVatCode:"1",defaultVatPct:25},
  {code:"1280",name:"Kontormaskiner",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe A: Kontormaskiner mv.",saftCode13:"1280"},
  {code:"1281",name:"Akk avskrivning kontormaskiner 1280",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe A: Kontormaskiner mv.",saftCode13:"1280"},
  {code:"1290",name:"Andre driftsmidler",accountType:"Balanse - eiendeler",balanceGroup:"Driftsmiddel som avskrives lineært",saftCode13:"1290",defaultVatCode:"1",defaultVatPct:25},
  {code:"1291",name:"Andre driftsmidler, ikke avskrivbare",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel",saftCode13:"1290",defaultVatCode:"1",defaultVatPct:25},
  // 13 Finansielle anleggsmidler
  {code:"1300",name:"Investeringer i datterselskap",accountType:"Balanse - eiendeler",saftCode13:"1313"},
  {code:"1310",name:"Investeringer i annet foretak i samme konsern",accountType:"Balanse - eiendeler",saftCode13:"1313"},
  {code:"1312",name:"Investeringer i deltakerliknede datter- og konsernselskap",accountType:"Balanse - eiendeler",saftCode13:"1312"},
  {code:"1330",name:"Investeringer i tilknyttete selskap",accountType:"Balanse - eiendeler",saftCode13:"1332"},
  {code:"1340",name:"Lån til tilknyttet selskap og felles kontrollert virksomhet",accountType:"Balanse - eiendeler",saftCode13:"1340"},
  {code:"1350",name:"Investeringer i aksjer, andeler og verdipapirfondsandeler",accountType:"Balanse - eiendeler",saftCode13:"1350"},
  {code:"1360",name:"Obligasjoner",accountType:"Balanse - eiendeler",saftCode13:"1360"},
  {code:"1370",name:"Fordringer på eiere",accountType:"Balanse - eiendeler",saftCode13:"1370"},
  {code:"1375",name:"Fordringer på styremedlemmer",accountType:"Balanse - eiendeler",saftCode13:"1370"},
  {code:"1380",name:"Fordringer på ansatte",accountType:"Balanse - eiendeler",saftCode13:"1380"},
  {code:"1394",name:"Overfinansiering av pensjonsforpliktelser",accountType:"Balanse - eiendeler",saftCode13:"1395"},
  {code:"1395",name:"Leietakerinnskudd",accountType:"Balanse - eiendeler",saftCode13:"1395"},
  {code:"1396",name:"Depositum",accountType:"Balanse - eiendeler",saftCode13:"1390"},
  {code:"1397",name:"Forskuddsleasing",accountType:"Balanse - eiendeler",saftCode13:"1390"},
  {code:"1398",name:"Påkostning leide driftsmidler",accountType:"Balanse - eiendeler",balanceGroup:"Driftsmiddel som avskrives lineært",saftCode13:"1290"},
  {code:"1399",name:"Andre fordringer",accountType:"Balanse - eiendeler",saftCode13:"1390"},
  // 14 Varelager og forskudd til leverandører
  {code:"1400",name:"Råvarer",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1401",name:"Halvfabrikata",accountType:"Balanse - eiendeler",saftCode13:"1401"},
  {code:"1405",name:"Hjelpematerialer",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1408",name:"Driftsmaterialer og reservedeler",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1409",name:"Beholdningsendring",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1420",name:"Varer under tilvirkning",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1429",name:"Beholdningsendring",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1440",name:"Ferdig egentilvirkede varer",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1449",name:"Beholdningsendring",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1460",name:"Innkjøpte varer for videresalg",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1465",name:"Demonstrasjonsvarer",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1469",name:"Beholdningsendring",accountType:"Balanse - eiendeler",saftCode13:"1400"},
  {code:"1480",name:"Forskuddsbetaling til leverandører",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1490",name:"Biologiske eiendeler",accountType:"Balanse - eiendeler",saftCode13:"1490"},
  // 15 Kortsiktige fordringer
  {code:"1500",name:"Kundefordringer",accountType:"Balanse - eiendeler",saftCode13:"1500"},
  {code:"1530",name:"Opptjent, ikke fakturert driftsinntekt",accountType:"Balanse - eiendeler",saftCode13:"1530"},
  {code:"1550",name:"Kundefordringer på selskap i samme konsern",accountType:"Balanse - eiendeler",saftCode13:"1501"},
  {code:"1560",name:"Andre fordringer på selskap i samme konsern",accountType:"Balanse - eiendeler",saftCode13:"1560"},
  {code:"1570",name:"Reiseforskudd",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1571",name:"Lønnsforskudd",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1572",name:"Andre kortsiktige lån til ansatte",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1575",name:"Forskudd refusjon skatt etter skatteloven § 16-50",accountType:"Balanse - eiendeler",saftCode13:"1565"},
  {code:"1576",name:"Kortsiktige fordringer eiere/styremedl. o.l.",accountType:"Balanse - eiendeler",saftCode13:"1565"},
  {code:"1579",name:"Andre kortsiktige fordringer",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1580",name:"Avsetning tap på kundefordringer",accountType:"Balanse - eiendeler",saftCode13:"1500"},
  {code:"1585",name:"Avsetning tap på andre fordringer",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1590",name:"Andre omløpsmidler",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  // 16 Merverdiavgift, opptjente offentlige tilskudd o.l.
  {code:"1600",name:"Utgående merverdiavgift, høy sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1601",name:"Utgående merverdiavgift, middels sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1602",name:"Utgående merverdiavgift, lav sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1603",name:"Utgående merverdiavgift kjøp av tjenester fra utlandet",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1610",name:"Inngående merverdiavgift, høy sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1611",name:"Inngående merverdiavgift, middels sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1612",name:"Inngående merverdiavgift, lav sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1613",name:"Direktepostert inngående merverdiavgift ved innførsel, høy sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1614",name:"Direktepostert inngående merverdiavgift ved innførsel, middels sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1640",name:"Oppgjørskonto merverdiavgift",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1650",name:"Kompensert merverdiavgift, høy sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1651",name:"Kompensert merverdiavgift, middels sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1652",name:"Kompensert merverdiavgift, lav sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1654",name:"Oppgjørskonto kompensert merverdiavgift",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1655",name:"Grunnlag kompensert merverdiavgift, høy sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1656",name:"Grunnlag kompensert merverdiavgift, middels sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1657",name:"Grunnlag kompensert merverdiavgift, lav sats",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1659",name:"Motkonto grunnlag kompensert merverdiavgift",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1670",name:"Krav på offentlige tilskudd",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  // 17 Forskuddsbetalt kostnad, påløpt inntekt o.l.
  {code:"1700",name:"Forskuddsbetalt leiekostnad",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1710",name:"Forskuddsbetalt rentekostnad",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1720",name:"Andre depositum",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1740",name:"Forskuddsbetalt, ikke påløpt lønn",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1741",name:"Forskuddsbetalt strøm, varme m.v.",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1742",name:"Forskuddsbetalt forsikring",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1743",name:"Forskuddsbetalt leasing (kortsiktig)",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1749",name:"Andre forskuddsbetalte kostnader",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1750",name:"Påløpt leieinntekt",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1760",name:"Påløpt renteinntekt",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1770",name:"Andre periodiseringer",accountType:"Balanse - eiendeler",saftCode13:"1570"},
  {code:"1780",name:"Krav på innbetaling av selskapskapital",accountType:"Balanse - eiendeler",saftCode13:"1780"},
  {code:"1790",name:"Bank åpne poster",accountType:"Balanse - eiendeler",saftCode13:"1780"},
  // 18 Kortsiktige finansinvesteringer
  {code:"1800",name:"Aksjer og andeler i foretak i samme konsern",accountType:"Balanse - eiendeler",saftCode13:"1800"},
  {code:"1810",name:"Markedsbaserte aksjer og verdipapirfondsandeler",accountType:"Balanse - eiendeler",saftCode13:"1810"},
  {code:"1820",name:"Andre aksjer",accountType:"Balanse - eiendeler",saftCode13:"1800"},
  {code:"1830",name:"Markedsbaserte obligasjoner",accountType:"Balanse - eiendeler",saftCode13:"1830"},
  {code:"1840",name:"Andre obligasjoner",accountType:"Balanse - eiendeler",saftCode13:"1840"},
  {code:"1850",name:"Markedsbaserte obligasjoner med kort løpetid (sertifikater)",accountType:"Balanse - eiendeler",saftCode13:"1840"},
  {code:"1860",name:"Andre obligasjoner med kort løpetid (sertifikater)",accountType:"Balanse - eiendeler",saftCode13:"1840"},
  {code:"1870",name:"Andre markedsbaserte finansielle instrumenter",accountType:"Balanse - eiendeler",saftCode13:"1880"},
  {code:"1880",name:"Andre finansielle instrumenter",accountType:"Balanse - eiendeler",saftCode13:"1880"},
  // 19 Kontanter, bankinnskudd o.l.
  {code:"1900",name:"Kontanter NOK",accountType:"Balanse - eiendeler",saftCode13:"1900"},
  {code:"1908",name:"Kontanter annen valuta",accountType:"Balanse - eiendeler",saftCode13:"1900"},
  {code:"1909",name:"Kassedifferanser",accountType:"Balanse - eiendeler",saftCode13:"1900"},
  {code:"1920",name:"Bankinnskudd S Banken utgår",accountType:"Balanse - eiendeler",saftCode13:"1920"},
  {code:"1921",name:"Bankinnskudd - ledig",accountType:"Balanse - eiendeler",saftCode13:"1920"},
  {code:"1940",name:"Bankinnskudd utland",accountType:"Balanse - eiendeler",saftCode13:"1920"},
  {code:"1950",name:"Bankinnskudd for skattetrekk Sbanken - utgår",accountType:"Balanse - eiendeler",saftCode13:"1950"},
  // 20 Egenkapital AS/ASA / Egenkapital andre foretak (inkl. samvirkeforetak)
  {code:"2000",name:"Aksjekapital",accountType:"Balanse - egenkapital",saftCode13:"2000"},
  {code:"2010",name:"Egne aksjer",accountType:"Balanse - egenkapital",saftCode13:"2010"},
  {code:"2020",name:"Overkurs",accountType:"Balanse - egenkapital",saftCode13:"2020"},
  {code:"2025",name:"Ikke registrert kapitalforhøyelse/kapitalnedsettelse",accountType:"Balanse - egenkapital",saftCode13:"2020"},
  {code:"2030",name:"Annen innskutt egenkapital",accountType:"Balanse - egenkapital",saftCode13:"2030"},
  {code:"2041",name:"Fond for vurderingsforskjeller",accountType:"Balanse - egenkapital",saftCode13:"2041"},
  {code:"2042",name:"Fond for vurderingsforskjeller i deltakerlignende selskap",accountType:"Balanse - egenkapital",saftCode13:"2042"},
  {code:"2045",name:"Fond for verdiendringer i andre selskap",accountType:"Balanse - egenkapital",saftCode13:"2045"},
  {code:"2050",name:"Annen egenkapital",accountType:"Balanse - egenkapital",saftCode13:"2050"},
  {code:"2051",name:"Ikke fradragsberettigede representasjonskostnader",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2052",name:"Ikke fradragsberettigede kontigenter/gaver",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2053",name:"Andre ikke fradragsberettigede kostnader",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2054",name:"Skattefrie inntekter",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2055",name:"Innskudd kontanter",accountType:"Balanse - egenkapital",saftCode13:"2055"},
  {code:"2056",name:"Innskudd andre eiendeler",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2057",name:"Fradragsført bruk av privat bil etter sats",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2058",name:"Øvrige egenkapitalkorreksjoner",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2061",name:"Kontantuttak",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2063",name:"Uttak av driftsmidler",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2064",name:"Uttak av varer og tjenester",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2065",name:"Egen bolig i næringsbygg",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2067",name:"Lys og varme privat",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2068",name:"Private kostnader til elektronisk kommunikasjon",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2069",name:"Diverse andre private kostnader",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2072",name:"Skatter",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2075",name:"Privat bruk av næringsbil",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2077",name:"Premie til egen syke- og ulykkesforsikring",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2078",name:"Premie til tilleggstrygd for sykepenger",accountType:"Balanse - egenkapital",saftCode13:"NA"},
  {code:"2080",name:"Udekket tap",accountType:"Balanse - egenkapital",saftCode13:"2080"},
  {code:"2099",name:"Overføringer annen egenkapital",accountType:"Balanse - egenkapital",saftCode13:"2080"},
  // 21 Avsetning for forpliktelser
  {code:"2100",name:"Pensjonsforpliktelser",accountType:"Balanse - gjeld",saftCode13:"2100"},
  {code:"2120",name:"Utsatt skatt",accountType:"Balanse - gjeld",saftCode13:"2120"},
  {code:"2160",name:"Uopptjent inntekt",accountType:"Balanse - gjeld",saftCode13:"2160"},
  {code:"2180",name:"Andre avsetninger for forpliktelser",accountType:"Balanse - gjeld",saftCode13:"2180"},
  // 22 Annen langsiktig gjeld
  {code:"2200",name:"Konvertible lån",accountType:"Balanse - gjeld",saftCode13:"2200"},
  {code:"2210",name:"Obligasjonslån",accountType:"Balanse - gjeld",saftCode13:"2210"},
  {code:"2220",name:"Gjeld til kredittinstitusjoner",accountType:"Balanse - gjeld",saftCode13:"2220"},
  {code:"2240",name:"Pantelån",accountType:"Balanse - gjeld",saftCode13:"2220"},
  {code:"2250",name:"Gjeld til ansatte og eiere",accountType:"Balanse - gjeld",saftCode13:"2250"},
  {code:"2260",name:"Gjeld til selskap i samme konsern",accountType:"Balanse - gjeld",saftCode13:"2260"},
  {code:"2270",name:"Andre valutalån",accountType:"Balanse - gjeld",saftCode13:"2290"},
  {code:"2280",name:"Stille interessentinnskudd og ansvarlig lånekapital",accountType:"Balanse - gjeld",saftCode13:"2280"},
  {code:"2290",name:"Annen langsiktig gjeld",accountType:"Balanse - gjeld",saftCode13:"2290"},
  // 23 Kortsiktige konvertible lån, obligasjonslån og gjeld til kredittinstitusjoner
  {code:"2300",name:"Konvertible lån",accountType:"Balanse - gjeld",saftCode13:"2310"},
  {code:"2320",name:"Obligasjonslån",accountType:"Balanse - gjeld",saftCode13:"2320"},
  {code:"2340",name:"Andre valutalån",accountType:"Balanse - gjeld",saftCode13:"2380"},
  {code:"2360",name:"Byggelån",accountType:"Balanse - gjeld",saftCode13:"2380"},
  {code:"2380",name:"Kassakreditt",accountType:"Balanse - gjeld",saftCode13:"2380"},
  {code:"2390",name:"Annen gjeld til kredittinstitusjon",accountType:"Balanse - gjeld",saftCode13:"2380"},
  // 24 Leverandørgjeld
  {code:"2400",name:"Leverandørgjeld",accountType:"Balanse - gjeld",saftCode13:"2400"},
  {code:"2460",name:"Leverandørgjeld til selskap i samme konsern",accountType:"Balanse - gjeld",saftCode13:"2460"},
  // 25 Betalbar skatt
  {code:"2500",name:"Betalbar skatt, ikke utlignet",accountType:"Balanse - gjeld",saftCode13:"2500"},
  {code:"2510",name:"Betalbar skatt, utlignet",accountType:"Balanse - gjeld",saftCode13:"2510"},
  {code:"2530",name:"Refusjon skatt etter skatteloven § 16-50",accountType:"Balanse - gjeld",saftCode13:"2510"},
  {code:"2540",name:"Forhåndsskatt",accountType:"Balanse - gjeld",saftCode13:"2510"},
  // 26 Skattetrekk og andre trekk
  {code:"2600",name:"Forskuddstrekk",accountType:"Balanse - gjeld",saftCode13:"2600"},
  {code:"2610",name:"Utleggstrekk",accountType:"Balanse - gjeld",saftCode13:"2600"},
  {code:"2620",name:"Bidragstrekk",accountType:"Balanse - gjeld",saftCode13:"2600"},
  {code:"2630",name:"Trygdetrekk",accountType:"Balanse - gjeld",saftCode13:"2600"},
  {code:"2640",name:"Forsikringstrekk",accountType:"Balanse - gjeld",saftCode13:"2600"},
  {code:"2650",name:"Trukket fagforeningskontingent",accountType:"Balanse - gjeld",saftCode13:"2600"},
  {code:"2670",name:"Trukket lavtlønnsfond",accountType:"Balanse - gjeld",saftCode13:"2600"},
  {code:"2690",name:"Andre trekk",accountType:"Balanse - gjeld",saftCode13:"2600"},
  // 27 Skyldige offentlige avgifter
  {code:"2700",name:"Utgående merverdiavgift, høy sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2701",name:"Utgående merverdiavgift, middels sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2702",name:"Utgående merverdiavgift, lav sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2703",name:"Utgående merverdiavgift kjøp av tjenester fra utlandet, høy sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2704",name:"Utgående merverdiavgift kjøp av tjenester fra utlandet, lav sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2705",name:"Utgående merverdiavgift innførsel, høy sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2706",name:"Utgående merverdiavgift innførsel, middels sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2707",name:"Utgående merverdiavgift kjøp av klimakvoter og gull",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2710",name:"Inngående merverdiavgift, høy sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2711",name:"Inngående merverdiavgift, middels sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2712",name:"Inngående merverdiavgift, lav sats",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2713",name:"Direktepostert inngående merverdiavgift ved innførsel, høy sats",accountType:"Balanse - gjeld",saftCode13:"2740"},  // source Mva-kode 14 not yet supported
  {code:"2714",name:"Direktepostert inngående merverdiavgift ved innførsel, middels sats",accountType:"Balanse - gjeld",saftCode13:"2740"},  // source Mva-kode 15 not yet supported
  {code:"2740",name:"Oppgjørskonto merverdiavgift",accountType:"Balanse - gjeld",saftCode13:"2740"},
  {code:"2770",name:"Skyldig arbeidsgiveravgift",accountType:"Balanse - gjeld",saftCode13:"2770"},
  {code:"2771",name:"Skyldig finansskatt av lønn",accountType:"Balanse - gjeld",saftCode13:"2770"},
  {code:"2780",name:"Påløpt arbeidsgiveravgift på påløpt lønn",accountType:"Balanse - gjeld",saftCode13:"2770"},
  {code:"2785",name:"Påløpt arbeidsgiveravgift på ferielønn",accountType:"Balanse - gjeld",saftCode13:"2770"},
  {code:"2786",name:"Påløpt finansskatt av ferielønn",accountType:"Balanse - gjeld",saftCode13:"2770"},
  {code:"2790",name:"Andre offentlige avgifter",accountType:"Balanse - gjeld",saftCode13:"2790"},
  // 28 Utbytte
  {code:"2800",name:"Avsatt utbytte",accountType:"Balanse - gjeld",saftCode13:"2800"},
  // 29 Annen kortsiktig gjeld
  {code:"2900",name:"Forskudd fra kunder",accountType:"Balanse - gjeld",saftCode13:"2900"},
  {code:"2910",name:"Gjeld til ansatte og eiere",accountType:"Balanse - gjeld",saftCode13:"2910"},
  {code:"2915",name:"Mellomværende Trygve",accountType:"Balanse - gjeld",saftCode13:"2910"},
  {code:"2920",name:"Gjeld til selskap i samme konsern",accountType:"Balanse - gjeld",saftCode13:"2920"},
  {code:"2930",name:"Skyldig lønn",accountType:"Balanse - gjeld",saftCode13:"2949"},
  {code:"2940",name:"Skyldig feriepenger",accountType:"Balanse - gjeld",saftCode13:"2949"},
  {code:"2945",name:"Periodisering av lønn",accountType:"Balanse - gjeld",saftCode13:"2949"},
  {code:"2950",name:"Påløpt rente",accountType:"Balanse - gjeld",saftCode13:"2950"},
  {code:"2960",name:"Annen påløpt kostnad",accountType:"Balanse - gjeld",saftCode13:"2990",defaultVatCode:"1",defaultVatPct:25},
  {code:"2965",name:"Forskuddsbetalt inntekt",accountType:"Balanse - gjeld",saftCode13:"2990"},
  {code:"2970",name:"Uopptjent inntekt",accountType:"Balanse - gjeld",saftCode13:"2970"},
  {code:"2980",name:"Avsetning styrehonorar",accountType:"Balanse - gjeld",saftCode13:"2980"},
  {code:"2981",name:"Avsetning revisjonshonorar",accountType:"Balanse - gjeld",saftCode13:"2980"},
  {code:"2982",name:"Avsetning regnskapshonorar",accountType:"Balanse - gjeld",saftCode13:"2980"},
  {code:"2989",name:"Avsetning andre forpliktelser",accountType:"Balanse - gjeld",saftCode13:"2980"},
  {code:"2990",name:"Annen kortsiktig gjeld",accountType:"Balanse - gjeld",saftCode13:"2990"},
  // 30 Salgsinntekt, avgiftspliktig
  {code:"3000",name:"Salgsinntekt, avgiftspliktig",accountType:"Resultat - driftsinntekt",saftCode13:"3000",defaultVatCode:"3",defaultVatPct:25},
  {code:"3001",name:"Salgsinntekt, avgiftspliktig, middels sats",accountType:"Resultat - driftsinntekt",saftCode13:"3001",defaultVatCode:"31",defaultVatPct:15},
  {code:"3002",name:"Salgsinntekt, avgiftspliktig, lav sats",accountType:"Resultat - driftsinntekt",saftCode13:"3002",defaultVatCode:"33",defaultVatPct:12},
  {code:"3011",name:"Salgsinntekt, avgiftspliktig, råfisk",accountType:"Resultat - driftsinntekt",saftCode13:"3000",defaultVatCode:"32",defaultVatPct:11.11},
  {code:"3060",name:"Uttak av varer/tjenester",accountType:"Resultat - driftsinntekt",saftCode13:"3000",defaultVatCode:"3",defaultVatPct:25},
  {code:"3061",name:"Uttak av varer/tjenester, middels sats",accountType:"Resultat - driftsinntekt",saftCode13:"3000",defaultVatCode:"31",defaultVatPct:15},
  {code:"3062",name:"Uttak av varer/tjenester, lav sats",accountType:"Resultat - driftsinntekt",saftCode13:"3000",defaultVatCode:"33",defaultVatPct:12},
  {code:"3063",name:"Motkonto uttak av varer/tjenester",accountType:"Resultat - driftsinntekt",saftCode13:"3000"},
  {code:"3080",name:"Rabatt og annen salgsinntektsreduksjon",accountType:"Resultat - driftsinntekt",saftCode13:"3000",defaultVatCode:"3",defaultVatPct:25},
  {code:"3090",name:"Opptjent, ikke fakturert inntekt",accountType:"Resultat - driftsinntekt",saftCode13:"3000"},
  {code:"3092",name:"Motkonto salgsinntekt fisk, avgiftspliktig, medium sats",accountType:"Resultat - driftsinntekt",saftCode13:"3000"},
  {code:"3093",name:"Motkonto salgsinntekt, avgiftspliktig, lav sats",accountType:"Resultat - driftsinntekt",saftCode13:"3000"},
  {code:"3094",name:"Motkonto salgsinntekt, avgiftspliktig, medium sats",accountType:"Resultat - driftsinntekt",saftCode13:"3000"},
  {code:"3095",name:"Motkonto salgsinntekt, avgiftspliktig, høy sats",accountType:"Resultat - driftsinntekt",saftCode13:"3000"},
  // 31 Salgsinntekt, avgiftsfri
  {code:"3100",name:"Salgsinntekt, avgiftsfri",accountType:"Resultat - driftsinntekt",saftCode13:"3100",defaultVatCode:"5",defaultVatPct:0},
  {code:"3107",name:"Salgsinntekt utførsel av varer og tjenester, avgiftsfri",accountType:"Resultat - driftsinntekt",saftCode13:"3100",defaultVatCode:"52",defaultVatPct:0},
  {code:"3108",name:"Salgsinntekt gull og klimakvoter, avgiftsfri",accountType:"Resultat - driftsinntekt",saftCode13:"3100",defaultVatCode:"51",defaultVatPct:0},
  {code:"3160",name:"Uttak av varer/tjenester",accountType:"Resultat - driftsinntekt",saftCode13:"3100",defaultVatCode:"5",defaultVatPct:0},
  {code:"3180",name:"Rabatt og annen salgsinntektsreduksjon",accountType:"Resultat - driftsinntekt",saftCode13:"3100",defaultVatCode:"5",defaultVatPct:0},
  {code:"3190",name:"Opptjent, ikke fakturert inntekt",accountType:"Resultat - driftsinntekt",saftCode13:"3100"},
  {code:"3195",name:"Motkonto salgsinntekt, avgiftsfri",accountType:"Resultat - driftsinntekt",saftCode13:"3100"},
  {code:"3197",name:"Motkonto salgsinntekt utførsel av varer og tjenester, fritatt fra avgiftsplikt",accountType:"Resultat - driftsinntekt",saftCode13:"3100"},
  {code:"3198",name:"Motkonto salgsinntekt gull og klimakvoter, omvendt avgiftsplikt",accountType:"Resultat - driftsinntekt",saftCode13:"3100"},
  // 32 Salgsinntekt, unntatt avgiftsplikt
  {code:"3200",name:"Salgsinntekt, utenfor avgiftsområdet",accountType:"Resultat - driftsinntekt",saftCode13:"3200",defaultVatCode:"6",defaultVatPct:0},
  {code:"3260",name:"Uttak av varer/tjenester",accountType:"Resultat - driftsinntekt",saftCode13:"3200",defaultVatCode:"6",defaultVatPct:0},
  {code:"3280",name:"Rabatt og annen salgsinntektsreduksjon",accountType:"Resultat - driftsinntekt",saftCode13:"3200",defaultVatCode:"6",defaultVatPct:0},
  {code:"3290",name:"Opptjent, ikke fakturert inntekt",accountType:"Resultat - driftsinntekt",saftCode13:"3200"},
  {code:"3295",name:"Motkonto salgsinntekt, utenfor avgiftsområdet",accountType:"Resultat - driftsinntekt",saftCode13:"3200"},
  // 33 Offentlig avgift vedrørende omsetning
  {code:"3300",name:"Spesiell offentlig avgift for tilvirkede/solgte varer",accountType:"Resultat - driftsinntekt",saftCode13:"3300"},
  // 34 Offentlig tilskudd/refusjon
  {code:"3400",name:"Spesielt offentlig tilskudd for tilvirkede/solgte varer",accountType:"Resultat - driftsinntekt",saftCode13:"3400"},
  {code:"3440",name:"Spesielt offentlig tilskudd for tjeneste",accountType:"Resultat - driftsinntekt",saftCode13:"3400"},
  // 36 Leieinntekt
  {code:"3600",name:"Leieinntekt fast eiendom, avgiftspliktig",accountType:"Resultat - driftsinntekt",saftCode13:"3600",defaultVatCode:"3",defaultVatPct:25},
  {code:"3605",name:"Leieinntekt fast eiendom utenfor avgiftsområdet",accountType:"Resultat - driftsinntekt",saftCode13:"3600",defaultVatCode:"6",defaultVatPct:0},
  {code:"3610",name:"Leieinntekt andre varige driftsmidler avgiftspliktig",accountType:"Resultat - driftsinntekt",saftCode13:"3695",defaultVatCode:"3",defaultVatPct:25},
  {code:"3615",name:"Leieinntekt andre varige driftsmidler avgiftsfri",accountType:"Resultat - driftsinntekt",saftCode13:"3695",defaultVatCode:"5",defaultVatPct:0},
  {code:"3620",name:"Annen leieinntekt",accountType:"Resultat - driftsinntekt",saftCode13:"3695",defaultVatCode:"6",defaultVatPct:0},
  {code:"3690",name:"Opptjent, ikke fakturert leieinntekt",accountType:"Resultat - driftsinntekt",saftCode13:"3695"},
  // 37 Provisjonsinntekt
  {code:"3700",name:"Provisjonsinntekt, avgiftspliktig",accountType:"Resultat - driftsinntekt",saftCode13:"3700",defaultVatCode:"3",defaultVatPct:25},
  {code:"3705",name:"Provisjonsinntekt, avgiftsfri",accountType:"Resultat - driftsinntekt",saftCode13:"3700",defaultVatCode:"5",defaultVatPct:0},
  {code:"3710",name:"Provisjonsinntekt, utenfor avgiftsområdet",accountType:"Resultat - driftsinntekt",saftCode13:"3710",defaultVatCode:"6",defaultVatPct:0},
  {code:"3790",name:"Opptjent, ikke fakturert provisjon",accountType:"Resultat - driftsinntekt",saftCode13:"3700"},
  // 38 Gevinst ved avgang av anleggsmidler (konto 380-384 samt 388-389). Verdiendring (konto 385-389).
  {code:"3800",name:"Salgssum anleggsmidler, avgiftspliktig",accountType:"Resultat - driftsinntekt",saftCode13:"3900",defaultVatCode:"3",defaultVatPct:25},
  {code:"3805",name:"Salgssum anleggsmidler, avgiftsfri",accountType:"Resultat - driftsinntekt",saftCode13:"3900",defaultVatCode:"5",defaultVatPct:0},
  {code:"3806",name:"Salgssum anleggsmidler, avgiftsfri - Tillegpostering",accountType:"Resultat - driftsinntekt",saftCode13:"3900"},
  {code:"3807",name:"Salgssum anleggsmidler, utenfor avgiftsområdet",accountType:"Resultat - driftsinntekt",saftCode13:"3900",defaultVatCode:"6",defaultVatPct:0},
  {code:"3809",name:"Motkonto, balanseverdi solgte anleggsmidler",accountType:"Resultat - driftsinntekt",saftCode13:"3900"},
  {code:"3850",name:"Verdiendringer investeringseiendommer",accountType:"Resultat - driftsinntekt",saftCode13:"3850"},
  {code:"3870",name:"Verdiendringer biologiske eiendeler",accountType:"Resultat - driftsinntekt",saftCode13:"3870"},
  // 39 Annen driftsrelatert inntekt
  {code:"3900",name:"Annen driftsrelatert inntekt",accountType:"Resultat - driftsinntekt",saftCode13:"3900"},
  // 40 Forbruk av råvarer og innkjøpte halvfabrikata
  {code:"4000",name:"Innkjøp av råvarer og halvfabrikater",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4060",name:"Frakt, toll og spedisjon",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4070",name:"Innkjøpsprisreduksjon",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4090",name:"Beholdningsendring",accountType:"Resultat - driftskostnad",saftCode13:"4005"},
  // 41 Forbruk av varer under tilvirkning
  {code:"4100",name:"Innkjøp varer under tilvirkning",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4160",name:"Frakt, toll og spedisjon",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4170",name:"Innkjøpsprisreduksjon",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4190",name:"Beholdningsendring",accountType:"Resultat - driftskostnad",saftCode13:"4295"},
  // 42 Forbruk av ferdig tilvirkede varer
  {code:"4200",name:"Innkjøp ferdig egentilvirkede varer",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4260",name:"Frakt, toll og spedisjon",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4270",name:"Innkjøpsprisreduksjon",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4290",name:"Beholdningsendring",accountType:"Resultat - driftskostnad",saftCode13:"4295"},
  // 43 Forbruk av innkjøpte varer for videresalg
  {code:"4300",name:"Innkjøp av varer for videresalg",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4301",name:"Innkjøp av varer for videresalg u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"4005"},
  {code:"4302",name:"Avfall",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4350",name:"Svinn, tap",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4360",name:"Frakt, toll og spedisjon",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4370",name:"Innkjøpsprisreduksjon",accountType:"Resultat - driftskostnad",saftCode13:"4005",defaultVatCode:"1",defaultVatPct:25},
  {code:"4380",name:"Grunnlag merverdiavgift ved innførsel",accountType:"Resultat - driftskostnad",saftCode13:"4005"},
  {code:"4390",name:"Beholdningsendring",accountType:"Resultat - driftskostnad",saftCode13:"4005"},
  {code:"4400",name:"Innkjøp av varer for videresalg - utland",accountType:"Resultat - driftskostnad",saftCode13:"4005"},  // source Mva-kode 21 not yet supported
  // 45 Fremmedytelse og underentreprise
  {code:"4500",name:"Fremmedytelse og underentreprise",accountType:"Resultat - driftskostnad",saftCode13:"4500",defaultVatCode:"1",defaultVatPct:25},
  {code:"4501",name:"Fremmedytelse og underentreprise u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"4500"},
  {code:"4520",name:"Under-entreprenører oppgavepliktig",accountType:"Resultat - driftskostnad",saftCode13:"4500",defaultVatCode:"1",defaultVatPct:25},
  {code:"4590",name:"Beholdningsendring",accountType:"Resultat - driftskostnad",saftCode13:"4500"},
  // 49 Annen periodisering
  {code:"4900",name:"Annen periodisering",accountType:"Resultat - driftskostnad",saftCode13:"4995"},
  {code:"4990",name:"Beholdningsendring egentilvirkede anleggsmidler",accountType:"Resultat - driftskostnad",saftCode13:"4995"},
  // 50 Lønn til ansatte
  {code:"5000",name:"Lønn til ansatte",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5001",name:"Lønn u/Feriepenger",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5020",name:"Feriepenger",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5030",name:"Sykepenger",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5090",name:"Påløpt, ikke utbetalt lønn",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5091",name:"Påløpte feriepenger av ikke utbetalt lønn",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5095",name:"Periodisering av lønn",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5096",name:"Periodisering av feriepenger",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5099",name:"Andre lønnsperiodiseringer",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  // 52 Fordel i arbeidsforhold
  {code:"5200",name:"Fri bil",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5210",name:"Fri telefon",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5220",name:"Fri avis",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5230",name:"Fri kost, losji og bolig",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5240",name:"Rentefordel",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5251",name:"Gruppelivsforsikring",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5252",name:"Ulykkesforsikring",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5280",name:"Annen fordel i arbeidsforhold",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5285",name:"Annen fordel i arbeidsforhold - ikke arbeidsgiveravgiftspliktig",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5290",name:"Motkonto for gruppe 52",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  // 53 Annen opplysningspliktig godtgjørelse
  {code:"5300",name:"Tantieme",accountType:"Resultat - driftskostnad",saftCode13:"5300"},
  {code:"5310",name:"Gruppelivsforsikring",accountType:"Resultat - driftskostnad",saftCode13:"5300"},
  {code:"5320",name:"Annen oppgavepliktig personalforsikring",accountType:"Resultat - driftskostnad",saftCode13:"5300"},
  {code:"5330",name:"Godtgjørelse til styre- og bedriftsforsamling",accountType:"Resultat - driftskostnad",saftCode13:"5300",defaultVatCode:"1",defaultVatPct:25},
  {code:"5390",name:"Annen oppgavepliktig godtgjørelse",accountType:"Resultat - driftskostnad",saftCode13:"5300"},
  {code:"5395",name:"Annen oppgavepliktig godtgjørelse - ikke arbeidsgiveravgiftspliktig",accountType:"Resultat - driftskostnad",saftCode13:"5300"},
  // 54 Arbeidsgiveravgift og pensjonskostnad
  {code:"5400",name:"Arbeidsgiveravgift",accountType:"Resultat - driftskostnad",saftCode13:"5400"},
  {code:"5401",name:"Arbeidsgiveravgift av opptjente feriepenger",accountType:"Resultat - driftskostnad",saftCode13:"5400"},
  {code:"5405",name:"Arbeidsgiveravgift av andre påløpte lønnskostnader",accountType:"Resultat - driftskostnad",saftCode13:"5400"},
  {code:"5420",name:"Innberetningspliktig pensjonskostnad",accountType:"Resultat - driftskostnad",saftCode13:"5420"},
  {code:"5430",name:"Finansskatt av lønn",accountType:"Resultat - driftskostnad",saftCode13:"5400"},
  {code:"5431",name:"Finansskatt av påløpt ferielønn",accountType:"Resultat - driftskostnad",saftCode13:"5400"},
  {code:"5495",name:"Periodisering av arbeidsgiveravgift",accountType:"Resultat - driftskostnad",saftCode13:"5400"},
  {code:"5496",name:"Periodisering av arbeidsgiveravgift av opptjente feriepenger",accountType:"Resultat - driftskostnad",saftCode13:"5400"},
  // 55 Annen kostnadsgodtgjørelse
  {code:"5500",name:"Annen kostnadsgodtgjørelse",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5510",name:"Trekkpliktig del av reise",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  // 56 Arbeidsgodtgjørelse til eiere o.l.
  {code:"5600",name:"Arbeidsgodtgjørelse til eiere i ANS o.l.",accountType:"Resultat - driftskostnad",saftCode13:"5600"},
  // 57 Offentlig tilskudd vedrørende arbeidskraft
  {code:"5700",name:"Lærlingtilskudd",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5720",name:"Annet lønnstilskudd",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  // 58 Offentlig refusjon vedrørende arbeidskraft
  {code:"5800",name:"Refusjon av sykepenger",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5820",name:"Refusjon av arbeidsgiveravgift",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5830",name:"Refusjon arbeidsmarkedstiltak",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  {code:"5890",name:"Annen refusjon",accountType:"Resultat - driftskostnad",saftCode13:"5000"},
  // 59 Annen personalkostnad
  {code:"5900",name:"Gave til ansatte, fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5901",name:"Gave til ansatte, ikke fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5910",name:"Kantinekostnad",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5912",name:"Middag ved overtid",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5919",name:"Trekk kantinekostnad ansatte",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5920",name:"Yrkesskadeforsikring",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5930",name:"Annen ikke arbeidsgiveravgiftspliktig forsikring",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5941",name:"LO/NHO ( O & U + sluttvederlag)",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5942",name:"LO/NHO ( AFP )",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5945",name:"Pensjonsforsikring for ansatte",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5970",name:"Innberetningspliktig fritidsforsikring",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  {code:"5990",name:"Annen personalkostnad",accountType:"Resultat - driftskostnad",saftCode13:"5900"},
  // 60 Av- og nedskrivning
  {code:"6000",name:"Avskrivning på bygninger og annen fast eiendom",accountType:"Resultat - driftskostnad",saftCode13:"6000"},
  {code:"6010",name:"Avskriving på transportmidler",accountType:"Resultat - driftskostnad",saftCode13:"6000"},
  {code:"6015",name:"Avskrivning på maskiner",accountType:"Resultat - driftskostnad",saftCode13:"6000"},
  {code:"6017",name:"Avskrivning på inventar",accountType:"Resultat - driftskostnad",saftCode13:"6000"},
  {code:"6020",name:"Avskrivning på immaterielle eiendeler",accountType:"Resultat - driftskostnad",saftCode13:"6000"},
  {code:"6050",name:"Nedskrivning på varige driftsmidler og immaterielle eiendeler",accountType:"Resultat - driftskostnad",saftCode13:"6050"},
  // 61 Frakt og transportkostnad vedrørende salg
  {code:"6100",name:"Frakt, transportkostnad og forsikring ved vareforsendelse",accountType:"Resultat - driftskostnad",saftCode13:"6100",defaultVatCode:"1",defaultVatPct:25},
  {code:"6110",name:"Toll og spedisjonskostnad ved vareforsendelse",accountType:"Resultat - driftskostnad",saftCode13:"6110",defaultVatCode:"1",defaultVatPct:25},
  {code:"6190",name:"Annen frakt- og transportkostnad ved salg",accountType:"Resultat - driftskostnad",saftCode13:"6100",defaultVatCode:"1",defaultVatPct:25},
  // 62 Energi, brensel og vann vedrørende produksjon
  {code:"6200",name:"Elektrisitet",accountType:"Resultat - driftskostnad",saftCode13:"6200",defaultVatCode:"1",defaultVatPct:25},
  {code:"6210",name:"Gass",accountType:"Resultat - driftskostnad",saftCode13:"6200",defaultVatCode:"1",defaultVatPct:25},
  {code:"6220",name:"Fyringsolje",accountType:"Resultat - driftskostnad",saftCode13:"6200",defaultVatCode:"1",defaultVatPct:25},
  {code:"6230",name:"Kull, koks",accountType:"Resultat - driftskostnad",saftCode13:"6200",defaultVatCode:"1",defaultVatPct:25},
  {code:"6240",name:"Ved",accountType:"Resultat - driftskostnad",saftCode13:"6200",defaultVatCode:"1",defaultVatPct:25},
  {code:"6250",name:"Bensin, dieselolje",accountType:"Resultat - driftskostnad",saftCode13:"6200",defaultVatCode:"1",defaultVatPct:25},
  {code:"6260",name:"Vann",accountType:"Resultat - driftskostnad",saftCode13:"6200",defaultVatCode:"1",defaultVatPct:25},
  {code:"6290",name:"Annet brensel",accountType:"Resultat - driftskostnad",saftCode13:"6200",defaultVatCode:"1",defaultVatPct:25},
  // 63 Kostnad lokaler
  {code:"6300",name:"Leie lokale",accountType:"Resultat - driftskostnad",saftCode13:"6300",defaultVatCode:"1",defaultVatPct:25},
  {code:"6301",name:"Leie lokale -  u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6300"},
  {code:"6320",name:"Renovasjon, vann, avløp o.l.",accountType:"Resultat - driftskostnad",saftCode13:"6395",defaultVatCode:"1",defaultVatPct:25},
  {code:"6340",name:"Lys, varme",accountType:"Resultat - driftskostnad",saftCode13:"6340",defaultVatCode:"1",defaultVatPct:25},
  {code:"6360",name:"Renhold",accountType:"Resultat - driftskostnad",saftCode13:"6395",defaultVatCode:"1",defaultVatPct:25},
  {code:"6390",name:"Annen kostnad lokaler",accountType:"Resultat - driftskostnad",saftCode13:"6395",defaultVatCode:"1",defaultVatPct:25},
  // 64 Leie maskiner, inventar, o.l.
  {code:"6400",name:"Leie maskiner",accountType:"Resultat - driftskostnad",saftCode13:"6400",defaultVatCode:"1",defaultVatPct:25},
  {code:"6410",name:"Leie inventar",accountType:"Resultat - driftskostnad",saftCode13:"6400",defaultVatCode:"1",defaultVatPct:25},
  {code:"6420",name:"Leie datasystemer",accountType:"Resultat - driftskostnad",saftCode13:"6400",defaultVatCode:"1",defaultVatPct:25},
  {code:"6421",name:"Leie datasysteme u/mva",accountType:"Resultat - driftskostnad",saftCode13:"6400"},
  {code:"6422",name:"Leie datasystemer - Utland",accountType:"Resultat - driftskostnad",saftCode13:"6400"},
  {code:"6430",name:"Leie andre kontormaskiner",accountType:"Resultat - driftskostnad",saftCode13:"6400",defaultVatCode:"1",defaultVatPct:25},
  {code:"6440",name:"Leie transportmidler",accountType:"Resultat - driftskostnad",saftCode13:"6440",defaultVatCode:"1",defaultVatPct:25},
  {code:"6441",name:"Leie transportmidler u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6440"},
  {code:"6490",name:"Annen leiekostnad",accountType:"Resultat - driftskostnad",saftCode13:"6400",defaultVatCode:"1",defaultVatPct:25},
  // 65 Verktøy, inventar og driftsmateriale som ikke skal aktiveres
  {code:"6500",name:"Motordrevet verktøy",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6510",name:"Håndverktøy",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6520",name:"Hjelpeverktøy",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6530",name:"Spesialverktøy",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6540",name:"Inventar",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6541",name:"Inventar u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6500"},
  {code:"6550",name:"Driftsmateriale",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6551",name:"Datautstyr (hardware)",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6552",name:"Datautstyr (software)",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6553",name:"Datautstyr (hardware) u/mva",accountType:"Resultat - driftskostnad",saftCode13:"6500"},
  {code:"6560",name:"Rekvisita",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6570",name:"Arbeidsklær og verneutstyr",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6571",name:"Arbeidsklær uten MVA fradrag",accountType:"Resultat - driftskostnad",saftCode13:"6500"},
  {code:"6590",name:"Annet driftsmateriale m/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6500",defaultVatCode:"1",defaultVatPct:25},
  {code:"6591",name:"Annet driftsmateriale u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6500"},
  // 66 Reparasjon og vedlikehold
  {code:"6600",name:"Reparasjon og vedlikehold bygninger",accountType:"Resultat - driftskostnad",saftCode13:"6600",defaultVatCode:"1",defaultVatPct:25},
  {code:"6620",name:"Reparasjon og vedlikehold utstyr",accountType:"Resultat - driftskostnad",saftCode13:"6695",defaultVatCode:"1",defaultVatPct:25},
  {code:"6690",name:"Reparasjon og vedlikehold annet",accountType:"Resultat - driftskostnad",saftCode13:"6695",defaultVatCode:"1",defaultVatPct:25},
  // 67 Fremmed tjeneste
  {code:"6701",name:"Honorar revisjon",accountType:"Resultat - driftskostnad",saftCode13:"6700",defaultVatCode:"1",defaultVatPct:25},
  {code:"6702",name:"Honorar rådgivning revisjon",accountType:"Resultat - driftskostnad",saftCode13:"6700",defaultVatCode:"1",defaultVatPct:25},
  {code:"6705",name:"Honorar regnskap Apex",accountType:"Resultat - driftskostnad",saftCode13:"6700",defaultVatCode:"1",defaultVatPct:25},
  {code:"6706",name:"Honorar regnskap ECIT",accountType:"Resultat - driftskostnad",saftCode13:"6700",defaultVatCode:"1",defaultVatPct:25},
  {code:"6720",name:"Honorar for økonomisk rådgivning",accountType:"Resultat - driftskostnad",saftCode13:"6700",defaultVatCode:"1",defaultVatPct:25},
  {code:"6725",name:"Honorar for juridisk bistand, fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"6700",defaultVatCode:"1",defaultVatPct:25},
  {code:"6726",name:"Honorar for juridisk bistand, ikke fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"6700",defaultVatCode:"1",defaultVatPct:25},
  {code:"6790",name:"Annen fremmed tjeneste",accountType:"Resultat - driftskostnad",saftCode13:"6700",defaultVatCode:"1",defaultVatPct:25},
  {code:"6791",name:"Annen fremmed tjeneste u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6700"},
  // 68 Kontorkostnad, trykksak o.l.
  {code:"6800",name:"Kontorrekvisita",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  {code:"6810",name:"Data/EDB-kostnad",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  {code:"6820",name:"Trykksak",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  {code:"6840",name:"Aviser, tidsskrifter, bøker o.l.",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  {code:"6860",name:"Møte, kurs, oppdatering o.l. m/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  {code:"6861",name:"Møte, kurs, oppdatering o.l. u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6995"},
  {code:"6890",name:"Annen kontorkostnad",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  // 69 Telefon og porto o.l.
  {code:"6900",name:"Telefon",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  {code:"6901",name:"Telefon u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"6995"},
  {code:"6910",name:"Mobiltelefon",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  {code:"6940",name:"Porto",accountType:"Resultat - driftskostnad",saftCode13:"6995",defaultVatCode:"1",defaultVatPct:25},
  // 70 Kostnad transportmidler
  {code:"7000",name:"Drivstoff, selskapets transportmidler",accountType:"Resultat - driftskostnad",saftCode13:"7000",defaultVatCode:"1",defaultVatPct:25},
  {code:"7020",name:"Vedlikehold, selskapets transportmidler",accountType:"Resultat - driftskostnad",saftCode13:"7020",defaultVatCode:"1",defaultVatPct:25},
  {code:"7021",name:"Vedlikehold, personbil",accountType:"Resultat - driftskostnad",saftCode13:"7020"},
  {code:"7040",name:"Forsikring, selskapets transportmidler",accountType:"Resultat - driftskostnad",saftCode13:"7040"},
  {code:"7050",name:"Lisens kjørebok",accountType:"Resultat - driftskostnad",saftCode13:"7000",defaultVatCode:"1",defaultVatPct:25},
  {code:"7080",name:"Bilkostnader, bruk av privat bil i næring",accountType:"Resultat - driftskostnad",saftCode13:"7080"},
  {code:"7090",name:"Annen kostnad, selskapets transportmidler m/MVA",accountType:"Resultat - driftskostnad",saftCode13:"7020",defaultVatCode:"1",defaultVatPct:25},
  {code:"7091",name:"Annen kostnad, selskapets transportmidler u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"7020"},
  {code:"7092",name:"Traffik forsikring avgift",accountType:"Resultat - driftskostnad",saftCode13:"7099"},
  // 71 Kostnad og godtgjørelse for reise, diett, bil, o.l.
  {code:"7100",name:"Bilgodtgjørelse oppgavepliktig",accountType:"Resultat - driftskostnad",saftCode13:"7155"},
  {code:"7130",name:"Reisekostnad, oppgavepliktig",accountType:"Resultat - driftskostnad",saftCode13:"7155"},
  {code:"7140",name:"Reisekostnad, ikke oppgavepliktig",accountType:"Resultat - driftskostnad",saftCode13:"7165",defaultVatCode:"13",defaultVatPct:12},
  {code:"7141",name:"Reisekostnad, ikke oppgavepliktig u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"7165"},
  {code:"7142",name:"Reisekostnad, ikke oppgavepliktig - 25 MVA",accountType:"Resultat - driftskostnad",saftCode13:"7330"},
  {code:"7144",name:"Parkering u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"7155"},
  {code:"7148",name:"Bompenger",accountType:"Resultat - driftskostnad",saftCode13:"7165"},
  {code:"7150",name:"Diettkostnad, oppgavepliktig",accountType:"Resultat - driftskostnad",saftCode13:"7155"},
  {code:"7160",name:"Diettkostnad, ikke oppgavepliktig",accountType:"Resultat - driftskostnad",saftCode13:"7165"},
  {code:"7190",name:"Annen kostnadsgodtgjørelse",accountType:"Resultat - driftskostnad",saftCode13:"7165",defaultVatCode:"1",defaultVatPct:25},
  // 72 Provisjonskostnad
  {code:"7200",name:"Provisjonskostnad, oppgavepliktig",accountType:"Resultat - driftskostnad",saftCode13:"7295",defaultVatCode:"1",defaultVatPct:25},
  {code:"7210",name:"Provisjonskostnad, ikke oppgavepliktig",accountType:"Resultat - driftskostnad",saftCode13:"7295",defaultVatCode:"1",defaultVatPct:25},
  // 73 Salgs-, reklame- og representasjonskostnader
  {code:"7300",name:"Salgskostnad",accountType:"Resultat - driftskostnad",saftCode13:"7330",defaultVatCode:"1",defaultVatPct:25},
  {code:"7320",name:"Reklamekostnad",accountType:"Resultat - driftskostnad",saftCode13:"7330",defaultVatCode:"1",defaultVatPct:25},
  {code:"7350",name:"Representasjon, fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"7350"},
  {code:"7360",name:"Representasjon, ikke fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"7370"},
  {code:"7390",name:"Annen salgskostnad",accountType:"Resultat - driftskostnad",saftCode13:"7330",defaultVatCode:"1",defaultVatPct:25},
  // 74 Kontingent og gave
  {code:"7400",name:"Kontingent, fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"7400",defaultVatCode:"1",defaultVatPct:25},
  {code:"7410",name:"Kontingent, ikke fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"7490",defaultVatCode:"1",defaultVatPct:25},
  {code:"7420",name:"Gave, fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"7420"},
  {code:"7430",name:"Gave, ikke fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"7440"},
  // 75 Forsikringspremie, garanti- og servicekostnad
  {code:"7500",name:"Forsikringspremie",accountType:"Resultat - driftskostnad",saftCode13:"7500"},
  {code:"7550",name:"Garantikostnad",accountType:"Resultat - driftskostnad",saftCode13:"7565",defaultVatCode:"1",defaultVatPct:25},
  {code:"7560",name:"Servicekostnad",accountType:"Resultat - driftskostnad",saftCode13:"7565",defaultVatCode:"1",defaultVatPct:25},
  // 76 Lisens- og patentkostnad
  {code:"7600",name:"Lisensavgift og royalties",accountType:"Resultat - driftskostnad",saftCode13:"7600",defaultVatCode:"1",defaultVatPct:25},
  {code:"7610",name:"Patentkostnad ved egen patent",accountType:"Resultat - driftskostnad",saftCode13:"7600",defaultVatCode:"1",defaultVatPct:25},
  {code:"7620",name:"Kostnad ved varemerke o.l.",accountType:"Resultat - driftskostnad",saftCode13:"7600",defaultVatCode:"1",defaultVatPct:25},
  {code:"7630",name:"Kontroll-, prøve- og stempelavgift",accountType:"Resultat - driftskostnad",saftCode13:"7600",defaultVatCode:"1",defaultVatPct:25},
  // 77 Annen kostnad
  {code:"7700",name:"Styre- og bedriftsforsamlingsmøter",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  {code:"7710",name:"Generalforsamling",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  {code:"7730",name:"Kostnad ved egne aksjer",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  {code:"7740",name:"Øredifferanser",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  {code:"7750",name:"Eiendoms- og festeavgift",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  {code:"7770",name:"Bank og kortgebyrer",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  {code:"7790",name:"Annen kostnad, fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"7700",defaultVatCode:"1",defaultVatPct:25},
  {code:"7791",name:"Annen kostnad, ikke fradragsberettiget",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  {code:"7793",name:"Annen kostnad, fradragsberettiget u/MVA",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  // 78 Tap o.l.
  {code:"7800",name:"Tap ved avgang av anleggsmidler",accountType:"Resultat - driftskostnad",saftCode13:"7830",defaultVatCode:"1",defaultVatPct:25},
  {code:"7805",name:"Salgssum anleggsmidler avgiftsfri",accountType:"Resultat - driftskostnad",saftCode13:"7830",defaultVatCode:"1",defaultVatPct:25},
  {code:"7807",name:"Salgssum anleggsmidler utenfor avgiftsområdet",accountType:"Resultat - driftskostnad",saftCode13:"7830",defaultVatCode:"1",defaultVatPct:25},
  {code:"7809",name:"Motkonto balanseverdi solgte anleggsmidler",accountType:"Resultat - driftskostnad",saftCode13:"7830",defaultVatCode:"1",defaultVatPct:25},
  {code:"7820",name:"Innkommet på tidligere nedskrevne fordringer",accountType:"Resultat - driftskostnad",saftCode13:"7830",defaultVatCode:"1",defaultVatPct:25},
  {code:"7830",name:"Konstaterte tap på fordringer",accountType:"Resultat - driftskostnad",saftCode13:"7830"},
  {code:"7831",name:"Endring i avsetning tap på fordringer",accountType:"Resultat - driftskostnad",saftCode13:"7830"},
  {code:"7860",name:"Tap på kontrakter",accountType:"Resultat - driftskostnad",saftCode13:"7860"},
  // 79 Periodiseringskonto
  {code:"7900",name:"Beholdningsendring anlegg under utførelse",accountType:"Resultat - driftskostnad",saftCode13:"7700"},
  // 80 Finansinntekt
  {code:"8000",name:"Inntekt på investering i datterselskap",accountType:"Resultat - kapitalinntekt",saftCode13:"8079"},
  {code:"8010",name:"Inntekt på investering i annet foretak i samme konsern",accountType:"Resultat - kapitalinntekt",saftCode13:"8079"},
  {code:"8020",name:"Inntekt på investering i tilknyttet selskap",accountType:"Resultat - kapitalinntekt",saftCode13:"8079"},
  {code:"8030",name:"Renteinntekt fra foretak i samme konsern",accountType:"Resultat - kapitalinntekt",saftCode13:"8030"},
  {code:"8040",name:"Renteinntekt, skattefri",accountType:"Resultat - kapitalinntekt",saftCode13:"8050"},
  {code:"8050",name:"Annen renteinntekt",accountType:"Resultat - kapitalinntekt",saftCode13:"8050"},
  {code:"8060",name:"Valutagevinst (agio)",accountType:"Resultat - kapitalinntekt",saftCode13:"8060"},
  {code:"8070",name:"Annen finansinntekt",accountType:"Resultat - kapitalinntekt",saftCode13:"8079"},
  {code:"8071",name:"Aksjeutbytte",accountType:"Resultat - kapitalinntekt",saftCode13:"8090"},
  {code:"8078",name:"Gevinst ved realisasjon av aksjer",accountType:"Resultat - kapitalinntekt",saftCode13:"8074"},
  {code:"8080",name:"Verdiøkning av finansielle instrumenter vurdert til virkelig verdi",accountType:"Resultat - kapitalinntekt",saftCode13:"8080"},
  {code:"8090",name:"Inntekt av andre investeringer",accountType:"Resultat - kapitalinntekt",saftCode13:"8090"},
  // 81 Finanskostnad
  {code:"8100",name:"Verdireduksjon av finansielle instrumenter vurdert til virkelig verdi",accountType:"Resultat - kapitalkostnad",saftCode13:"8100"},
  {code:"8110",name:"Nedskrivning av andre finansielle omløpsmidler",accountType:"Resultat - kapitalkostnad",saftCode13:"8115"},
  {code:"8120",name:"Nedskrivning av finansielle anleggsmidler",accountType:"Resultat - kapitalkostnad",saftCode13:"8120"},
  {code:"8130",name:"Rentekostnad til foretak i samme konsern",accountType:"Resultat - kapitalkostnad",saftCode13:"8130"},
  {code:"8140",name:"Rentekostnad, ikke fradragsberettiget",accountType:"Resultat - kapitalkostnad",saftCode13:"8150"},
  {code:"8150",name:"Annen rentekostnad",accountType:"Resultat - kapitalkostnad",saftCode13:"8150"},
  {code:"8160",name:"Valutatap (disagio)",accountType:"Resultat - kapitalkostnad",saftCode13:"8160"},
  {code:"8170",name:"Annen finanskostnad",accountType:"Resultat - kapitalkostnad",saftCode13:"8179"},
  {code:"8175",name:"Aprilla Bank - Annen finanskostnad",accountType:"Resultat - kapitalkostnad",saftCode13:"8175"},
  {code:"8178",name:"Tap ved realisasjon av aksjer",accountType:"Resultat - kapitalkostnad",saftCode13:"8174"},
  // 83 Skattekostnad på ordinært resultat
  {code:"8300",name:"Betalbar skatt",accountType:"Resultat - skattekostnad på ordinært resultat",saftCode13:"8300"},
  {code:"8310",name:"Refusjon skatt etter skatteloven § 16-50",accountType:"Resultat - skattekostnad på ordinært resultat",saftCode13:"8300"},
  {code:"8320",name:"Endring utsatt skatt",accountType:"Resultat - skattekostnad på ordinært resultat",saftCode13:"8321"},
  // 84 Ekstraordinær inntekt
  {code:"8410",name:"Ekstraordinær gevinst ved salg av anleggsmidler",accountType:"Resultat - ekstraordinær inntekt",saftCode13:"NA"},
  {code:"8450",name:"Ekstraordinære offentlige tilskudd",accountType:"Resultat - ekstraordinær inntekt",saftCode13:"NA"},
  {code:"8490",name:"Annen ekstraordinær inntekt",accountType:"Resultat - ekstraordinær inntekt",saftCode13:"NA"},
  // 85 Ekstraordinær kostnad
  {code:"8510",name:"Ekstraordinær kostnad ved salg av anleggmidler",accountType:"Resultat - ekstraordinær kostnad",saftCode13:"NA"},
  {code:"8590",name:"Annen ekstraordinær kostnad",accountType:"Resultat - ekstraordinær kostnad",saftCode13:"NA"},
  // 86 Skattekostnad på ekstraordinært resultat
  {code:"8600",name:"Betalbar skatt",accountType:"Resultat - skattekostnad på ekstraordinært resultat",saftCode13:"8300"},
  {code:"8610",name:"Refusjon skatt etter skatteloven § 16-50",accountType:"Resultat - skattekostnad på ekstraordinært resultat",saftCode13:"8300"},
  {code:"8620",name:"Endring utsatt skatt/skattefordel",accountType:"Resultat - skattekostnad på ekstraordinært resultat",saftCode13:"8321"},
  // 88 Årsresultat
  {code:"8800",name:"Årsresultat",accountType:"Resultat - årsresultat",saftCode13:"8800"},
  // 89 Overføringer og disponeringer
  {code:"8900",name:"Overføringer fond",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8910",name:"Overføringer felleseid andelskapital for samvirkeforetak",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8920",name:"Avsatt utbytte",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8930",name:"Mottatt konsernbidrag",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8935",name:"Avsatt konsernbidrag",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8940",name:"Mottatt aksjonærbidrag",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8945",name:"Avsatt aksjonærbidrag",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8950",name:"Fondsemisjon",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8960",name:"Overføringer annen egenkapital",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8969",name:"Avsatt til dekning av tidligere udekket tap",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"8990",name:"Udekket tap",accountType:"Resultat - overføringer og disponeringer",saftCode13:"NA"},
  {code:"9999",name:"Hjelpekonto",accountType:"Balanse - eiendeler",saftCode13:"NA"},
].map(a=>({...a,matchable:a.code==="1500"||a.code==="2400"}));

export { DEFAULT_ACCOUNTS };
