const DEFAULT_ACCOUNTS=[
  // ── 1000s ASSETS ──────────────────────────────────────────────
  // Fixed Assets (1000–1099)
  {code:"1000",name:"Fixed Assets",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1010",name:"Land & Buildings"},
  {code:"1020",name:"Office Buildings",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1030",name:"Other Real Estate",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1080",name:"Goodwill",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe B: Ervervet forretningsverdi"},
  // Intangible Assets (1100–1199)
  {code:"1100",name:"Intangible Assets",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe I: Forretningsbygg"},
  {code:"1110",name:"Research & Development"},
  {code:"1120",name:"Patents & Licenses",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe H: Bygg og anlegg mv."},
  {code:"1130",name:"Goodwill",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1190",name:"Other Fixed Assets",accountType:"Balanse - eiendeler",balanceGroup:"Driftsmiddel som avskrives lineært"},
  // Machinery & Equipment (1200–1399)
  {code:"1200",name:"Machinery & Plant",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1210",name:"Production Equipment",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1220",name:"Furniture & Fixtures",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe E: Skip, fartøyer mv."},
  {code:"1230",name:"Office Equipment",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe C: Vogntog, lastebiler mv."},
  {code:"1240",name:"Computer Equipment",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1249",name:"Other Transport Equipment",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1250",name:"Fixtures & Tools",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1260",name:"Vehicles",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1270",name:"Tools",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1280",name:"Office Machines",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe A: Kontormaskiner mv."},
  {code:"1290",name:"Other Operating Equipment",accountType:"Balanse - eiendeler",balanceGroup:"Driftsmiddel som avskrives lineært"},
  // Inventory & Stock (1400–1499)
  {code:"1400",name:"Inventory — Raw Materials",accountType:"Balanse - eiendeler"},
  {code:"1410",name:"Inventory — Work in Progress"},
  {code:"1420",name:"Inventory — Finished Goods",accountType:"Balanse - eiendeler"},
  {code:"1460",name:"Inventory — Goods for Resale",accountType:"Balanse - eiendeler"},
  {code:"1480",name:"Prepayments to Suppliers",accountType:"Balanse - eiendeler"},
  // Accounts Receivable (1500–1599)
  {code:"1500",name:"Accounts Receivable",accountType:"Balanse - eiendeler"},
  {code:"1509",name:"Accounts Receivable — Not on Subledger"},
  {code:"1510",name:"Trade Receivables"},
  {code:"1520",name:"Receivables from Group Companies"},
  {code:"1530",name:"Other Short-term Receivables",accountType:"Balanse - eiendeler"},
  {code:"1570",name:"Travel Advances",accountType:"Balanse - eiendeler"},
  {code:"1571",name:"Salary Advances",accountType:"Balanse - eiendeler"},
  {code:"1579",name:"Other Short-term Receivables (Misc.)",accountType:"Balanse - eiendeler"},
  {code:"1580",name:"Provision for Bad Debts",accountType:"Balanse - eiendeler"},
  // Other Short-term Receivables (1600–1799)
  {code:"1600",name:"VAT Receivable",accountType:"Balanse - eiendeler"},
  {code:"1630",name:"Prepaid Expenses"},
  {code:"1700",name:"Short-term Investments",accountType:"Balanse - eiendeler"},
  {code:"1710",name:"Shares in Listed Companies",accountType:"Balanse - eiendeler"},
  {code:"1749",name:"Other Prepaid Expenses",accountType:"Balanse - eiendeler"},
  {code:"1750",name:"Accrued Rental Income",accountType:"Balanse - eiendeler"},
  {code:"1790",name:"Accrued Income (Other)",accountType:"Balanse - eiendeler"},
  {code:"1800",name:"Accrued Income",accountType:"Balanse - eiendeler"},
  // Bank & Cash (1900–1999)
  {code:"1900",name:"Cash in Hand",accountType:"Balanse - eiendeler"},
  {code:"1910",name:"Bank Account — Main"},
  {code:"1920",name:"Bank Account — Operations",accountType:"Balanse - eiendeler"},
  {code:"1940",name:"Bank Account — Foreign",accountType:"Balanse - eiendeler"},
  {code:"1950",name:"Petty Cash",accountType:"Balanse - eiendeler"},
  {code:"1951",name:"Bank Account — Withholding Tax",accountType:"Balanse - eiendeler"},
  // ── 2000s EQUITY & LIABILITIES ────────────────────────────────
  // Equity (2000–2099)
  {code:"2000",name:"Share Capital",accountType:"Balanse - egenkapital"},
  {code:"2020",name:"Share Premium Reserve",accountType:"Balanse - egenkapital"},
  {code:"2050",name:"Retained Earnings",accountType:"Balanse - egenkapital"},
  {code:"2055",name:"Owner's Cash Contribution",accountType:"Balanse - egenkapital"},
  {code:"2060",name:"Owner's Drawings"},
  {code:"2070",name:"Taxes (Equity)"},
  {code:"2080",name:"Profit / Loss This Year",accountType:"Balanse - egenkapital"},
  // Long-term Debt (2100–2299)
  {code:"2100",name:"Long-term Bank Loans",accountType:"Balanse - gjeld"},
  {code:"2110",name:"Mortgage Loans"},
  {code:"2130",name:"Loans from Shareholders"},
  {code:"2200",name:"Deferred Tax Liability",accountType:"Balanse - gjeld"},
  {code:"2220",name:"Debt to Credit Institutions",accountType:"Balanse - gjeld"},
  {code:"2290",name:"Other Provisions",accountType:"Balanse - gjeld"},
  {code:"2299",name:"Other Long-term Debt (Misc.)"},
  // Other Long-term Liabilities (2300–2399)
  {code:"2300",name:"Other Long-term Liabilities",accountType:"Balanse - gjeld"},
  {code:"2310",name:"Loans — Group Companies"},
  {code:"2360",name:"Construction Loan",accountType:"Balanse - gjeld"},
  {code:"2380",name:"Overdraft Facility",accountType:"Balanse - gjeld"},
  {code:"2390",name:"Other Debt to Credit Institutions",accountType:"Balanse - gjeld"},
  // Accounts Payable (2400–2499)
  {code:"2400",name:"Accounts Payable",accountType:"Balanse - gjeld"},
  {code:"2409",name:"Accounts Payable — Not on Subledger"},
  {code:"2410",name:"Trade Payables"},
  {code:"2420",name:"Payables to Group Companies"},
  // VAT & Tax Payable (2500–2599)
  {code:"2500",name:"VAT Payable — Output",accountType:"Balanse - gjeld"},
  {code:"2510",name:"VAT Collected",accountType:"Balanse - gjeld"},
  {code:"2520",name:"VAT — Input (Deductible)"},
  {code:"2540",name:"VAT Payable to Tax Authority",accountType:"Balanse - gjeld"},
  // Public Duties (2600–2699)
  {code:"2600",name:"Withholding Tax Payable",accountType:"Balanse - gjeld"},
  {code:"2610",name:"Social Security Contributions Payable",accountType:"Balanse - gjeld"},
  {code:"2620",name:"Holiday Pay Liability",accountType:"Balanse - gjeld"},
  {code:"2640",name:"Insurance Deductions Payable",accountType:"Balanse - gjeld"},
  {code:"2690",name:"Other Payroll Deductions",accountType:"Balanse - gjeld"},
  // Wages & Salaries Payable (2700–2799) — NOTE: the real Norwegian
  // NS 4102 standard uses this range for output/input VAT settlement
  // sub-accounts (2700 Utgående mva osv.), not payroll. These codes
  // were already in use here for payroll concepts before this
  // comparison, so they're left as-is to avoid breaking any company
  // that's already posted against them — see the VAT settlement
  // accounts added at 2701–2766 below instead, which is where a real
  // Norwegian chart actually expects that detail to live.
  {code:"2700",name:"Salaries Payable",accountType:"Balanse - gjeld"},
  {code:"2701",name:"Output VAT — Services Purchased Abroad",accountType:"Balanse - gjeld"},
  {code:"2702",name:"Output VAT — Medium Rate",accountType:"Balanse - gjeld"},
  {code:"2703",name:"Output VAT — Low Rate",accountType:"Balanse - gjeld"},
  {code:"2710",name:"Pension Contributions Payable",accountType:"Balanse - gjeld"},
  {code:"2711",name:"Input VAT — Services Purchased Abroad",accountType:"Balanse - gjeld"},
  {code:"2712",name:"Input VAT — Medium Rate",accountType:"Balanse - gjeld"},
  {code:"2713",name:"Input VAT — Low Rate",accountType:"Balanse - gjeld"},
  {code:"2720",name:"Employee Deductions Payable"},
  {code:"2727",name:"Output VAT — Goods Imported, High Rate"},
  {code:"2728",name:"Output VAT — Goods Imported, Medium Rate"},
  {code:"2740",name:"VAT Settlement Account",accountType:"Balanse - gjeld"},
  {code:"2741",name:"Input VAT — Goods Imported, High Rate"},
  {code:"2742",name:"Input VAT — Goods Imported, Medium Rate"},
  {code:"2745",name:"Basis — Output VAT, Services Purchased Abroad"},
  {code:"2746",name:"Contra — Basis, Services Purchased Abroad"},
  {code:"2761",name:"Basis — Goods Import, High Rate"},
  {code:"2762",name:"Contra — Basis, Goods Import High Rate"},
  {code:"2763",name:"Basis — Goods Import, Medium Rate"},
  {code:"2764",name:"Contra — Basis, Goods Import Medium Rate"},
  {code:"2765",name:"Basis — Goods Import, VAT-Free"},
  {code:"2766",name:"Contra — Basis, Goods Import VAT-Free"},
  {code:"2770",name:"Employer's Social Security Tax Payable",accountType:"Balanse - gjeld"},
  {code:"2780",name:"Accrued Employer's Tax — Payroll",accountType:"Balanse - gjeld"},
  {code:"2785",name:"Accrued Employer's Tax — Holiday Pay",accountType:"Balanse - gjeld"},
  // Short-term Debt (2800–2899)
  {code:"2800",name:"Short-term Bank Loans",accountType:"Balanse - gjeld"},
  {code:"2810",name:"Credit Facility"},
  // Other Current Liabilities (2900–2999)
  {code:"2900",name:"Accrued Expenses",accountType:"Balanse - gjeld"},
  {code:"2910",name:"Advance Payments from Customers",accountType:"Balanse - gjeld"},
  {code:"2930",name:"Salaries Payable (Unpaid)",accountType:"Balanse - gjeld"},
  {code:"2940",name:"Holiday Pay Payable",accountType:"Balanse - gjeld"},
  {code:"2950",name:"Other Current Liabilities",accountType:"Balanse - gjeld"},
  {code:"2970",name:"Deferred Revenue",accountType:"Balanse - gjeld"},
  {code:"2990",name:"Other Current Liabilities (Misc.)",accountType:"Balanse - gjeld"},
  // ── 3000s REVENUE ─────────────────────────────────────────────
  {code:"3000",name:"Sales Revenue",defaultVatCode:"3",defaultVatPct:25,accountType:"Resultat - driftsinntekt"},
  {code:"3010",name:"Sales — Goods",defaultVatCode:"3",defaultVatPct:25,accountType:"Resultat - driftsinntekt"},
  {code:"3020",name:"Sales — Services",defaultVatCode:"3",defaultVatPct:25},
  {code:"3030",name:"Sales — Projects",defaultVatCode:"3",defaultVatPct:25,accountType:"Resultat - driftsinntekt"},
  {code:"3035",name:"Sales — Goods, Low VAT Rate"},
  {code:"3050",name:"Sales — Services, Low VAT Rate"},
  {code:"3080",name:"Sales Discounts & Allowances",defaultVatCode:"3",defaultVatPct:25,accountType:"Resultat - driftsinntekt"},
  {code:"3100",name:"Sales Revenue — Export",defaultVatCode:"52",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3105",name:"Sales — Goods, Export (VAT-free)"},
  {code:"3120",name:"Sales — Services, Domestic VAT-Free"},
  {code:"3125",name:"Sales — Services, Export (VAT-free)"},
  {code:"3180",name:"Sales Discounts — VAT-Free",defaultVatCode:"5",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3200",name:"Sales Revenue — VAT Exempt",defaultVatCode:"5",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3220",name:"Sales — Services, Outside VAT Scope"},
  {code:"3280",name:"Sales Discounts — Outside VAT Scope",defaultVatCode:"6",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3400",name:"Public Grants & Subsidies",accountType:"Resultat - driftsinntekt"},
  {code:"3500",name:"Rental Income"},
  {code:"3600",name:"Commission Income",defaultVatCode:"3",defaultVatPct:25,accountType:"Resultat - driftsinntekt"},
  {code:"3800",name:"Gain on Disposal of Fixed Assets",defaultVatCode:"3",defaultVatPct:25,accountType:"Resultat - driftsinntekt"},
  {code:"3900",name:"Other Operating Income",accountType:"Resultat - driftsinntekt"},
  {code:"3910",name:"Postage Charged to Customers"},
  {code:"3950",name:"Handling Fees — VAT Free"},
  {code:"3960",name:"Gain on Asset Disposal"},
  // ── 4000s COST OF GOODS SOLD ─────────────────────────────────
  {code:"4000",name:"Cost of Goods Sold",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4010",name:"Purchases — Raw Materials",defaultVatCode:"1",defaultVatPct:25},
  {code:"4020",name:"Purchases — Goods for Resale",defaultVatCode:"1",defaultVatPct:25},
  {code:"4030",name:"Freight & Import Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4060",name:"Freight, Customs & Forwarding — Raw Materials",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4100",name:"Change in Inventory",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4300",name:"Purchases — Goods for Resale, Medium VAT",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4330",name:"Purchases — Goods for Resale, Low VAT",defaultVatCode:"11",defaultVatPct:15,accountType:"Resultat - driftskostnad"},
  {code:"4360",name:"Freight, Customs & Forwarding — Resale Goods",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4400",name:"Purchases — VAT Free",accountType:"Resultat - driftskostnad"},
  {code:"4500",name:"Subcontractors",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4600",name:"Direct Labour Costs",accountType:"Resultat - driftskostnad"},
  {code:"4800",name:"Handling Fees — Goods Purchases (VAT)"},
  {code:"4810",name:"Freight & Postage — Goods Purchases (VAT)"},
  {code:"4860",name:"Handling Fees — Goods Purchases (VAT-free)"},
  // ── 5000s PAYROLL & SALARIES ─────────────────────────────────
  {code:"5000",name:"Salaries & Wages",accountType:"Resultat - driftskostnad"},
  {code:"5010",name:"Salaries — Office Staff"},
  {code:"5020",name:"Salaries — Production Staff",accountType:"Resultat - driftskostnad"},
  {code:"5030",name:"Temporary / Contract Labour",accountType:"Resultat - driftskostnad"},
  {code:"5092",name:"Holiday Pay",accountType:"Resultat - driftskostnad"},
  {code:"5100",name:"Employer Social Security Tax"},
  {code:"5180",name:"Holiday Pay — Accrued"},
  {code:"5182",name:"Employer's Tax on Accrued Holiday Pay"},
  {code:"5192",name:"Holiday Pay — Hourly Staff"},
  {code:"5200",name:"Pension Contributions — Employer",accountType:"Resultat - driftskostnad"},
  {code:"5210",name:"Benefit — Company Phone",accountType:"Resultat - driftskostnad"},
  {code:"5220",name:"Benefit — Newspaper Subscription",accountType:"Resultat - driftskostnad"},
  {code:"5230",name:"Benefit — Board, Lodging & Housing",accountType:"Resultat - driftskostnad"},
  {code:"5251",name:"Group Life Insurance (Reportable)",accountType:"Resultat - driftskostnad"},
  {code:"5252",name:"Accident Insurance (Reportable)",accountType:"Resultat - driftskostnad"},
  {code:"5290",name:"Contra Account — Benefits (Group 52)",accountType:"Resultat - driftskostnad"},
  {code:"5300",name:"Holiday Pay Expense",accountType:"Resultat - driftskostnad"},
  {code:"5330",name:"Board & Committee Remuneration",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"5395",name:"Other Reportable Compensation (Tax-free)",accountType:"Resultat - driftskostnad"},
  {code:"5400",name:"Employee Benefits",accountType:"Resultat - driftskostnad"},
  {code:"5405",name:"Employer's Tax on Accrued Holiday Pay (Alt.)",accountType:"Resultat - driftskostnad"},
  {code:"5800",name:"Reimbursement — Sick Pay",accountType:"Resultat - driftskostnad"},
  {code:"5820",name:"Reimbursement — Employer's Social Tax",accountType:"Resultat - driftskostnad"},
  {code:"5900",name:"Other Personnel Costs",accountType:"Resultat - driftskostnad"},
  {code:"5910",name:"Canteen Costs",accountType:"Resultat - driftskostnad"},
  {code:"5950",name:"Mandatory Occupational Pension (OTP)"},
  {code:"5998",name:"Other Personnel Costs (Misc.)"},
  // ── 6000s DEPRECIATION ───────────────────────────────────────
  {code:"6000",name:"Depreciation — Buildings",accountType:"Resultat - driftskostnad"},
  {code:"6010",name:"Depreciation — Machinery & Equipment",accountType:"Resultat - driftskostnad"},
  {code:"6020",name:"Depreciation — Vehicles",accountType:"Resultat - driftskostnad"},
  {code:"6030",name:"Depreciation — IT Equipment"},
  {code:"6040",name:"Depreciation — Intangibles"},
  {code:"6100",name:"Write-down of Assets",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6110",name:"Customs & Forwarding Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6200",name:"Loss on Asset Disposal",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6250",name:"Fuel — Facilities",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6260",name:"Water",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6290",name:"Other Fuel/Heating",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6300",name:"Rent — Premises",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6320",name:"Waste, Water & Drainage",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6340",name:"Light & Heating",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6360",name:"Cleaning",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6390",name:"Other Premises Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6400",name:"Lease — Machinery",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6420",name:"Lease — IT Systems",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6490",name:"Other Lease Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6510",name:"Hand Tools",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6540",name:"Fixtures (Expensed)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6550",name:"Operating Supplies",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6560",name:"Consumables",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6570",name:"Workwear & Protective Equipment",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6590",name:"Other Operating Supplies",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6600",name:"Repairs & Maintenance — Buildings",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6620",name:"Repairs & Maintenance — Equipment",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6690",name:"Repairs & Maintenance — Other",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6700",name:"Audit & Accounting Fees"},
  {code:"6705",name:"Accounting Fees",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6720",name:"Legal & Financial Advisory Fees",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6780",name:"Central Government Fee",accountType:"Resultat - driftskostnad"},
  {code:"6781",name:"Central Government Fee — 25% VAT",accountType:"Resultat - driftskostnad"},
  {code:"6785",name:"Purchase of Services from Abroad"},
  {code:"6800",name:"Office Supplies (Expensed)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6810",name:"IT Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6820",name:"Printed Materials",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6840",name:"Newspapers, Journals & Books",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6860",name:"Meetings, Courses & Training",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6890",name:"Other Office Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6900",name:"Telephone",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6940",name:"Postage",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  // ── 7000s OPERATING EXPENSES ─────────────────────────────────
  {code:"7000",name:"Transport & Freight Expenses",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7001",name:"EV Charging",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7020",name:"Fuel",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7040",name:"Vehicle Running Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7090",name:"Other Vehicle Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7095",name:"Tolls"},
  {code:"7098",name:"Parking"},
  // Office & Admin (7100–7199)
  {code:"7100",name:"Office Supplies",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7110",name:"Printing & Stationery",defaultVatCode:"1",defaultVatPct:25},
  {code:"7120",name:"Postage & Courier",defaultVatCode:"1",defaultVatPct:25},
  {code:"7130",name:"Cleaning & Caretaking",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7140",name:"Electricity & Utilities",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7141",name:"Parking (Reportable)",accountType:"Resultat - driftskostnad"},
  {code:"7150",name:"Rent — Office",accountType:"Resultat - driftskostnad"},
  {code:"7160",name:"Lease Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7180",name:"Waste & Environmental Fees",defaultVatCode:"1",defaultVatPct:25},
  {code:"7190",name:"Other Expense Reimbursements",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  // Sales & Marketing (7200–7299)
  {code:"7200",name:"Advertising & Marketing",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7210",name:"Online Advertising",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7220",name:"Trade Fairs & Events",defaultVatCode:"1",defaultVatPct:25},
  {code:"7230",name:"Samples & Promotional Items",defaultVatCode:"1",defaultVatPct:25},
  {code:"7260",name:"Sales Commission",defaultVatCode:"1",defaultVatPct:25},
  // Travel & Entertainment (7300–7399)
  {code:"7300",name:"Travel Expenses",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7310",name:"Accommodation",defaultVatCode:"13",defaultVatPct:12},
  {code:"7320",name:"Meals & Entertainment",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7330",name:"Subsistence Allowance"},
  {code:"7350",name:"Representation (Tax-deductible)",accountType:"Resultat - driftskostnad"},
  {code:"7360",name:"Representation (Non-deductible)",accountType:"Resultat - driftskostnad"},
  {code:"7390",name:"VAT Rounding",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7395",name:"Rounding (Other)"},
  // IT & Telecom (7400–7499)
  {code:"7400",name:"IT & Software Costs",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7410",name:"Phone & Mobile",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7420",name:"Internet & Broadband",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7430",name:"Cloud & SaaS Subscriptions",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  // Insurance & Fees (7500–7599)
  {code:"7500",name:"Insurance Premiums",accountType:"Resultat - driftskostnad"},
  {code:"7510",name:"Legal & Professional Fees",defaultVatCode:"1",defaultVatPct:25},
  {code:"7520",name:"Accounting & Audit Fees",defaultVatCode:"1",defaultVatPct:25},
  {code:"7530",name:"Consulting Fees",defaultVatCode:"1",defaultVatPct:25},
  {code:"7540",name:"Membership Fees & Subscriptions"},
  {code:"7550",name:"Public Duties & Licence Fees",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  // Repairs & Maintenance (7600–7699)
  {code:"7600",name:"Repairs & Maintenance",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7610",name:"Maintenance — Buildings",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7620",name:"Maintenance — Equipment",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  // Finance & Bank (7700–7799)
  {code:"7700",name:"Bank Charges",accountType:"Resultat - driftskostnad"},
  {code:"7710",name:"Payment Transaction Fees",accountType:"Resultat - driftskostnad"},
  {code:"7720",name:"Interest Expense — Short-term"},
  {code:"7740",name:"Rounding — Other",accountType:"Resultat - driftskostnad"},
  {code:"7770",name:"Bank & Card Fees",accountType:"Resultat - driftskostnad"},
  {code:"7798",name:"Other Tax-deductible Expenses"},
  // Other Admin (7800–7899)
  {code:"7800",name:"Other Administrative Expenses",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7820",name:"Recovery of Previously Written-off Receivables",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7830",name:"Bad Debt Write-off",accountType:"Resultat - driftskostnad"},
  {code:"7890",name:"Miscellaneous Expenses",accountType:"Resultat - driftskostnad"},
  // Extraordinary (7900–7999)
  {code:"7900",name:"Extraordinary Expenses",accountType:"Resultat - driftskostnad"},
  // ── 8000s FINANCE ITEMS ───────────────────────────────────────
  {code:"8000",name:"Interest Income",accountType:"Resultat - kapitalinntekt"},
  {code:"8010",name:"Dividend Income",accountType:"Resultat - kapitalinntekt"},
  {code:"8020",name:"Gain on Sale of Investments",accountType:"Resultat - kapitalinntekt"},
  {code:"8030",name:"Currency Gain",accountType:"Resultat - kapitalinntekt"},
  {code:"8040",name:"Interest on Tax Refund (Tax-free)",accountType:"Resultat - kapitalinntekt"},
  {code:"8050",name:"Other Interest Income",accountType:"Resultat - kapitalinntekt"},
  {code:"8056",name:"Reminder Fee Income"},
  {code:"8060",name:"Currency Gain (Agio)",accountType:"Resultat - kapitalinntekt"},
  {code:"8070",name:"Other Financial Income",accountType:"Resultat - kapitalinntekt"},
  {code:"8100",name:"Interest Expense — Long-term",accountType:"Resultat - kapitalkostnad"},
  {code:"8110",name:"Currency Loss",accountType:"Resultat - kapitalkostnad"},
  {code:"8120",name:"Loss on Sale of Investments",accountType:"Resultat - kapitalkostnad"},
  {code:"8150",name:"Interest Expense — Credit Institutions",accountType:"Resultat - kapitalkostnad"},
  {code:"8160",name:"Currency Loss (Disagio)",accountType:"Resultat - kapitalkostnad"},
  {code:"8179",name:"Other Financial Expenses"},
  {code:"8300",name:"Extraordinary Income",accountType:"Resultat - skattekostnad på ordinært resultat"},
  {code:"8320",name:"Extraordinary Expense",accountType:"Resultat - skattekostnad på ordinært resultat"},
  {code:"8400",name:"Extraordinary Income (Alt.)"},
  {code:"8500",name:"Extraordinary Expense (Alt.)"},
  {code:"8800",name:"Income Tax Expense",accountType:"Resultat - årsresultat"},
  {code:"8810",name:"Deferred Tax Expense"},
  {code:"8928",name:"Private Use of Electronic Communication"},
  {code:"8960",name:"Transfers to Other Equity",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8990",name:"Uncovered Loss (Reserve)",accountType:"Resultat - overføringer og disponeringer"},
  // ── 9000s INTERNAL / CLEARING ─────────────────────────────────
  {code:"9000",name:"Internal Settlement Account"},
  {code:"9100",name:"Clearing Account"},
  {code:"9200",name:"Opening Balance Account"},

  // ── ADDED FROM TRIPLETEX'S FULL 572-ACCOUNT REFERENCE ──────────
  // Tripletex's export represents the complete, generic NS 4102
  // standard chart used across ordinary Norwegian firms (vs. Visma's
  // company export, which only listed accounts one specific taxi
  // business had actually activated — narrower and industry-skewed).
  // Company-specific rows (named bank accounts, a specific overdraft
  // facility, a named related-company balance) were excluded; only
  // generic standard codes are added here, as defaults for all firms.
  {code:"1005",name:"Research & Development (Self-developed)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1025",name:"Concessions (Self-developed)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1035",name:"Patents (Self-developed)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1040",name:"Licenses (Acquired)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1045",name:"Licenses (Self-developed)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1050",name:"Trademarks (Acquired)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1055",name:"Trademarks (Self-developed)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1060",name:"Other Rights (Acquired)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1065",name:"Other Rights (Self-developed)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1070",name:"Deferred Tax Asset",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1117",name:"Electrotechnical Equipment (Power Companies)",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe G: Anlegg for overføring og distribusjon av elektrisk kraft mv."},
  {code:"1140",name:"Agricultural Property",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1145",name:"Forestry Property",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1150",name:"Plots of Land",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1155",name:"Other Land Areas",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1160",name:"Residential Property incl. Land",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1180",name:"Investment Property",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe J: Fast teknisk installasjon i bygninger"},
  {code:"1224",name:"Rigs",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe E: Skip, fartøyer mv."},
  {code:"1225",name:"Aircraft",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe F: Fly og helikopter"},
  {code:"1233",name:"Vans",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe C: Vogntog, lastebiler mv."},
  {code:"1235",name:"Accum. Depreciation — Vans (1233)",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe C: Vogntog, lastebiler mv."},
  {code:"1242",name:"Trucks",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1243",name:"Tractors",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1248",name:"Forklifts",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1251",name:"Depreciation on Furniture & Fixtures (1250)",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1252",name:"Accum. Depreciation — Other Transport Equipment (1249)",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe D: Personbiler, traktorer mv."},
  {code:"1265",name:"Fixed Building Fixtures, Leased Premises",accountType:"Balanse - eiendeler",balanceGroup:"Driftsmiddel som avskrives lineært"},
  {code:"1281",name:"Accum. Depreciation — Office Machines (1280)",accountType:"Balanse - eiendeler",balanceGroup:"Saldogruppe A: Kontormaskiner mv."},
  {code:"1291",name:"Other Operating Equipment (Non-depreciable)",accountType:"Balanse - eiendeler",balanceGroup:"Ikke avskrivbart driftsmiddel"},
  {code:"1300",name:"Investments in Subsidiaries",accountType:"Balanse - eiendeler"},
  {code:"1310",name:"Investments in Other Group Companies",accountType:"Balanse - eiendeler"},
  {code:"1312",name:"Investments in Jointly Controlled Entities",accountType:"Balanse - eiendeler"},
  {code:"1330",name:"Investments in Associated Companies",accountType:"Balanse - eiendeler"},
  {code:"1340",name:"Loans to Associated & Jointly Controlled Companies",accountType:"Balanse - eiendeler"},
  {code:"1350",name:"Investments in Shares & Fund Units",accountType:"Balanse - eiendeler"},
  {code:"1360",name:"Bonds",accountType:"Balanse - eiendeler"},
  {code:"1370",name:"Receivables from Owners",accountType:"Balanse - eiendeler"},
  {code:"1375",name:"Receivables from Board Members",accountType:"Balanse - eiendeler"},
  {code:"1380",name:"Receivables from Employees",accountType:"Balanse - eiendeler"},
  {code:"1394",name:"Overfunded Pension Obligations",accountType:"Balanse - eiendeler"},
  {code:"1395",name:"Tenant Deposits Held",accountType:"Balanse - eiendeler"},
  {code:"1396",name:"Deposits",accountType:"Balanse - eiendeler"},
  {code:"1397",name:"Prepaid Leasing",accountType:"Balanse - eiendeler"},
  {code:"1398",name:"Improvements to Leased Assets",accountType:"Balanse - eiendeler",balanceGroup:"Driftsmiddel som avskrives lineært"},
  {code:"1399",name:"Other Receivables",accountType:"Balanse - eiendeler"},
  {code:"1401",name:"Semi-finished Goods",accountType:"Balanse - eiendeler"},
  {code:"1405",name:"Auxiliary Materials",accountType:"Balanse - eiendeler"},
  {code:"1408",name:"Operating Materials & Spare Parts",accountType:"Balanse - eiendeler"},
  {code:"1409",name:"Change in Inventory — Raw Materials",accountType:"Balanse - eiendeler"},
  {code:"1429",name:"Change in Inventory — Work in Progress",accountType:"Balanse - eiendeler"},
  {code:"1440",name:"Finished Self-produced Goods",accountType:"Balanse - eiendeler"},
  {code:"1449",name:"Change in Inventory — Finished Self-produced Goods",accountType:"Balanse - eiendeler"},
  {code:"1465",name:"Demonstration Goods",accountType:"Balanse - eiendeler"},
  {code:"1469",name:"Change in Inventory — Goods for Resale",accountType:"Balanse - eiendeler"},
  {code:"1490",name:"Biological Assets",accountType:"Balanse - eiendeler"},
  {code:"1550",name:"Trade Receivables — Group Companies",accountType:"Balanse - eiendeler"},
  {code:"1560",name:"Other Receivables — Group Companies",accountType:"Balanse - eiendeler"},
  {code:"1572",name:"Other Short-term Loans to Employees",accountType:"Balanse - eiendeler"},
  {code:"1575",name:"Advance — Tax Refund (Tax Act §16-50)",accountType:"Balanse - eiendeler"},
  {code:"1576",name:"Short-term Receivables from Owners/Board",accountType:"Balanse - eiendeler"},
  {code:"1585",name:"Provision for Losses on Other Receivables",accountType:"Balanse - eiendeler"},
  {code:"1590",name:"Other Current Assets",accountType:"Balanse - eiendeler"},
  {code:"1601",name:"Output VAT — Medium Rate",accountType:"Balanse - eiendeler"},
  {code:"1602",name:"Output VAT — Low Rate",accountType:"Balanse - eiendeler"},
  {code:"1603",name:"Output VAT — Services Purchased Abroad",accountType:"Balanse - eiendeler"},
  {code:"1610",name:"Input VAT — High Rate",accountType:"Balanse - eiendeler"},
  {code:"1611",name:"Input VAT — Medium Rate",accountType:"Balanse - eiendeler"},
  {code:"1612",name:"Input VAT — Low Rate",accountType:"Balanse - eiendeler"},
  {code:"1613",name:"Input VAT on Imports — High Rate",accountType:"Balanse - eiendeler"},
  {code:"1614",name:"Input VAT on Imports — Medium Rate",accountType:"Balanse - eiendeler"},
  {code:"1640",name:"VAT Settlement Account",accountType:"Balanse - eiendeler"},
  {code:"1650",name:"VAT Compensation — High Rate",accountType:"Balanse - eiendeler"},
  {code:"1651",name:"VAT Compensation — Medium Rate",accountType:"Balanse - eiendeler"},
  {code:"1652",name:"VAT Compensation — Low Rate",accountType:"Balanse - eiendeler"},
  {code:"1654",name:"VAT Compensation Settlement Account",accountType:"Balanse - eiendeler"},
  {code:"1655",name:"Basis — VAT Compensation, High Rate",accountType:"Balanse - eiendeler"},
  {code:"1656",name:"Basis — VAT Compensation, Medium Rate",accountType:"Balanse - eiendeler"},
  {code:"1657",name:"Basis — VAT Compensation, Low Rate",accountType:"Balanse - eiendeler"},
  {code:"1659",name:"Contra — Basis, VAT Compensation",accountType:"Balanse - eiendeler"},
  {code:"1670",name:"Public Grants Receivable",accountType:"Balanse - eiendeler"},
  {code:"1720",name:"Other Deposits",accountType:"Balanse - eiendeler"},
  {code:"1740",name:"Prepaid, Not Accrued Salary",accountType:"Balanse - eiendeler"},
  {code:"1741",name:"Prepaid Electricity & Heating",accountType:"Balanse - eiendeler"},
  {code:"1742",name:"Prepaid Insurance",accountType:"Balanse - eiendeler"},
  {code:"1743",name:"Prepaid Leasing (Short-term)",accountType:"Balanse - eiendeler"},
  {code:"1760",name:"Accrued Interest Income",accountType:"Balanse - eiendeler"},
  {code:"1770",name:"Other Accruals",accountType:"Balanse - eiendeler"},
  {code:"1780",name:"Called-up, Unpaid Share Capital",accountType:"Balanse - eiendeler"},
  {code:"1810",name:"Market-based Shares & Fund Units",accountType:"Balanse - eiendeler"},
  {code:"1820",name:"Other Shares",accountType:"Balanse - eiendeler"},
  {code:"1830",name:"Market-based Bonds",accountType:"Balanse - eiendeler"},
  {code:"1840",name:"Other Bonds",accountType:"Balanse - eiendeler"},
  {code:"1850",name:"Market-based Short-term Bonds (Certificates)",accountType:"Balanse - eiendeler"},
  {code:"1860",name:"Other Short-term Bonds (Certificates)",accountType:"Balanse - eiendeler"},
  {code:"1870",name:"Other Market-based Financial Instruments",accountType:"Balanse - eiendeler"},
  {code:"1880",name:"Other Financial Instruments",accountType:"Balanse - eiendeler"},
  {code:"1908",name:"Cash — Foreign Currency",accountType:"Balanse - eiendeler"},
  {code:"1909",name:"Cash Differences",accountType:"Balanse - eiendeler"},
  {code:"1921",name:"Bank Deposit — Unrestricted",accountType:"Balanse - eiendeler"},
  {code:"2010",name:"Treasury Shares",accountType:"Balanse - egenkapital"},
  {code:"2025",name:"Unregistered Capital Increase/Decrease",accountType:"Balanse - egenkapital"},
  {code:"2030",name:"Other Paid-in Capital",accountType:"Balanse - egenkapital"},
  {code:"2041",name:"Fund for Valuation Differences",accountType:"Balanse - egenkapital"},
  {code:"2042",name:"Fund for Valuation Differences — Partnership",accountType:"Balanse - egenkapital"},
  {code:"2045",name:"Fund for Fair Value Changes — Other Companies",accountType:"Balanse - egenkapital"},
  {code:"2051",name:"Non-deductible Representation Costs",accountType:"Balanse - egenkapital"},
  {code:"2052",name:"Non-deductible Membership Fees/Gifts",accountType:"Balanse - egenkapital"},
  {code:"2053",name:"Other Non-deductible Costs",accountType:"Balanse - egenkapital"},
  {code:"2054",name:"Tax-free Income",accountType:"Balanse - egenkapital"},
  {code:"2056",name:"Contribution of Other Assets",accountType:"Balanse - egenkapital"},
  {code:"2057",name:"Deduction — Private Vehicle Use at Standard Rate",accountType:"Balanse - egenkapital"},
  {code:"2058",name:"Other Equity Corrections",accountType:"Balanse - egenkapital"},
  {code:"2061",name:"Cash Withdrawals (Owner)",accountType:"Balanse - egenkapital"},
  {code:"2063",name:"Withdrawal of Fixed Assets (Owner)",accountType:"Balanse - egenkapital"},
  {code:"2064",name:"Withdrawal of Goods & Services (Owner)",accountType:"Balanse - egenkapital"},
  {code:"2065",name:"Own Home in Business Property",accountType:"Balanse - egenkapital"},
  {code:"2067",name:"Private Light & Heating",accountType:"Balanse - egenkapital"},
  {code:"2068",name:"Private Electronic Communication Costs",accountType:"Balanse - egenkapital"},
  {code:"2069",name:"Other Private Costs",accountType:"Balanse - egenkapital"},
  {code:"2072",name:"Taxes (Owner Drawings)",accountType:"Balanse - egenkapital"},
  {code:"2075",name:"Private Use of Business Vehicle",accountType:"Balanse - egenkapital"},
  {code:"2077",name:"Own Sickness & Accident Insurance Premium",accountType:"Balanse - egenkapital"},
  {code:"2078",name:"Supplementary Sick Pay Insurance Premium",accountType:"Balanse - egenkapital"},
  {code:"2099",name:"Transfers — Other Equity",accountType:"Balanse - egenkapital"},
  {code:"2120",name:"Deferred Tax",accountType:"Balanse - gjeld"},
  {code:"2160",name:"Unearned Income",accountType:"Balanse - gjeld"},
  {code:"2180",name:"Other Provisions for Liabilities",accountType:"Balanse - gjeld"},
  {code:"2210",name:"Bond Loan",accountType:"Balanse - gjeld"},
  {code:"2240",name:"Mortgage Loan",accountType:"Balanse - gjeld"},
  {code:"2250",name:"Debt to Employees & Owners",accountType:"Balanse - gjeld"},
  {code:"2260",name:"Debt to Group Companies",accountType:"Balanse - gjeld"},
  {code:"2270",name:"Other Foreign Currency Loans",accountType:"Balanse - gjeld"},
  {code:"2280",name:"Silent Partnership & Subordinated Loan Capital",accountType:"Balanse - gjeld"},
  {code:"2320",name:"Bond Loan (Short-term)",accountType:"Balanse - gjeld"},
  {code:"2340",name:"Other Foreign Currency Loans (Short-term)",accountType:"Balanse - gjeld"},
  {code:"2460",name:"Trade Payables — Group Companies",accountType:"Balanse - gjeld"},
  {code:"2530",name:"Tax Refund (Tax Act §16-50)",accountType:"Balanse - gjeld"},
  {code:"2630",name:"Social Security Deduction (Employee)",accountType:"Balanse - gjeld"},
  {code:"2650",name:"Union Dues Withheld",accountType:"Balanse - gjeld"},
  {code:"2670",name:"Low-income Fund Withheld",accountType:"Balanse - gjeld"},
  {code:"2704",name:"Output VAT — Services Purchased Abroad, Low Rate",accountType:"Balanse - gjeld"},
  {code:"2705",name:"Output VAT — Imports, High Rate",accountType:"Balanse - gjeld"},
  {code:"2706",name:"Output VAT — Imports, Medium Rate",accountType:"Balanse - gjeld"},
  {code:"2707",name:"Output VAT — Emission Allowances & Gold",accountType:"Balanse - gjeld"},
  {code:"2714",name:"Input VAT on Imports — Medium Rate (Direct-posted)",accountType:"Balanse - gjeld"},
  {code:"2771",name:"Financial Activity Tax on Salary Payable",accountType:"Balanse - gjeld"},
  {code:"2786",name:"Accrued Financial Activity Tax — Holiday Pay",accountType:"Balanse - gjeld"},
  {code:"2790",name:"Other Public Duties",accountType:"Balanse - gjeld"},
  {code:"2920",name:"Debt to Group Companies (Current)",accountType:"Balanse - gjeld"},
  {code:"2945",name:"Payroll Accrual",accountType:"Balanse - gjeld"},
  {code:"2960",name:"Other Accrued Expenses",accountType:"Balanse - gjeld"},
  {code:"2965",name:"Prepaid Income",accountType:"Balanse - gjeld"},
  {code:"2980",name:"Board Remuneration Accrual",accountType:"Balanse - gjeld"},
  {code:"2981",name:"Audit Fee Accrual",accountType:"Balanse - gjeld"},
  {code:"2982",name:"Accounting Fee Accrual",accountType:"Balanse - gjeld"},
  {code:"2989",name:"Other Liabilities Accrual",accountType:"Balanse - gjeld"},
  // "12" and "6" below were invalid/wrong MVA codes — "12" doesn't exist in
  // MVA_CODES at all (silently produced 0% VAT on any sale posted here
  // instead of erroring), and "6" is "outside VAT scope" (also 0%) when
  // this account is actually a normal 15% output sale. Corrected to the
  // real codes (31 = 15% output, 33 = 12% output) from utils.js MVA_CODES.
  {code:"3001",name:"Sales Revenue, Taxable, Medium Rate",defaultVatCode:"31",defaultVatPct:15,accountType:"Resultat - driftsinntekt"},
  {code:"3002",name:"Sales Revenue, Taxable, Low Rate",defaultVatCode:"33",defaultVatPct:12,accountType:"Resultat - driftsinntekt"},
  // Raw fish sales use Norway's special 11.11% rate (mva-kode 32), which
  // isn't modeled in this app's MVA_CODES list — left with no default
  // rather than a wrong one; whoever posts here picks the rate manually.
  {code:"3011",name:"Sales Revenue — Raw Fish",accountType:"Resultat - driftsinntekt"},
  {code:"3060",name:"Withdrawal of Goods/Services (Sales)",accountType:"Resultat - driftsinntekt"},
  {code:"3061",name:"Withdrawal of Goods/Services, Medium Rate",accountType:"Resultat - driftsinntekt"},
  {code:"3062",name:"Withdrawal of Goods/Services, Low Rate",accountType:"Resultat - driftsinntekt"},
  {code:"3063",name:"Contra — Withdrawal of Goods/Services",accountType:"Resultat - driftsinntekt"},
  {code:"3090",name:"Accrued, Not Invoiced Income",accountType:"Resultat - driftsinntekt"},
  {code:"3092",name:"Contra — Sales Revenue Fish, Taxable, Medium Rate",accountType:"Resultat - driftsinntekt"},
  {code:"3093",name:"Contra — Sales Revenue, Taxable, Low Rate",accountType:"Resultat - driftsinntekt"},
  {code:"3094",name:"Contra — Sales Revenue, Taxable, Medium Rate",accountType:"Resultat - driftsinntekt"},
  {code:"3095",name:"Contra — Sales Revenue, Taxable, High Rate",accountType:"Resultat - driftsinntekt"},
  {code:"3107",name:"Sales Revenue — Export of Goods/Services (VAT-free)",defaultVatCode:"52",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3108",name:"Sales Revenue — Gold & Emission Allowances (VAT-free)",defaultVatCode:"51",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3160",name:"Withdrawal of Goods/Services (VAT-free)",defaultVatCode:"5",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3190",name:"Accrued, Not Invoiced Income (VAT-free)",accountType:"Resultat - driftsinntekt"},
  {code:"3195",name:"Contra — Sales Revenue, VAT-free",accountType:"Resultat - driftsinntekt"},
  {code:"3197",name:"Contra — Sales Revenue, Export (VAT-exempt)",accountType:"Resultat - driftsinntekt"},
  {code:"3198",name:"Contra — Sales Revenue, Gold/Allowances (Reverse Charge)",accountType:"Resultat - driftsinntekt"},
  {code:"3260",name:"Withdrawal of Goods/Services (Outside VAT Scope)",defaultVatCode:"6",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3290",name:"Accrued, Not Invoiced Income (Outside VAT Scope)",accountType:"Resultat - driftsinntekt"},
  {code:"3295",name:"Contra — Sales Revenue, Outside VAT Scope",accountType:"Resultat - driftsinntekt"},
  {code:"3300",name:"Special Public Levy — Goods Produced/Sold",accountType:"Resultat - driftsinntekt"},
  {code:"3440",name:"Special Public Grant — Services",accountType:"Resultat - driftsinntekt"},
  {code:"3605",name:"Rental Income — Real Estate, Outside VAT Scope",defaultVatCode:"6",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3610",name:"Rental Income — Other Fixed Assets, Taxable",defaultVatCode:"3",defaultVatPct:25,accountType:"Resultat - driftsinntekt"},
  {code:"3615",name:"Rental Income — Other Fixed Assets, VAT-free",defaultVatCode:"5",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3620",name:"Other Rental Income",defaultVatCode:"6",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3690",name:"Accrued, Not Invoiced Rental Income",accountType:"Resultat - driftsinntekt"},
  {code:"3700",name:"Commission Income, Taxable",defaultVatCode:"3",defaultVatPct:25,accountType:"Resultat - driftsinntekt"},
  {code:"3705",name:"Commission Income, VAT-free",defaultVatCode:"5",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3710",name:"Commission Income, Outside VAT Scope",defaultVatCode:"6",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3790",name:"Accrued, Not Invoiced Commission",accountType:"Resultat - driftsinntekt"},
  {code:"3805",name:"Sale of Fixed Assets, VAT-free",defaultVatCode:"5",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3806",name:"Sale of Fixed Assets, VAT-free — Additional Posting",accountType:"Resultat - driftsinntekt"},
  {code:"3807",name:"Sale of Fixed Assets, Outside VAT Scope",defaultVatCode:"6",defaultVatPct:0,accountType:"Resultat - driftsinntekt"},
  {code:"3809",name:"Contra — Book Value of Fixed Assets Sold",accountType:"Resultat - driftsinntekt"},
  {code:"3850",name:"Value Changes — Investment Property",accountType:"Resultat - driftsinntekt"},
  {code:"3870",name:"Value Changes — Biological Assets",accountType:"Resultat - driftsinntekt"},
  {code:"4070",name:"Purchase Price Reduction — Raw Materials",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4090",name:"Change in Inventory — Raw Materials (Purchases)",accountType:"Resultat - driftskostnad"},
  {code:"4160",name:"Freight, Customs & Forwarding — Raw Materials (Alt.)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4170",name:"Purchase Price Reduction — Work in Progress",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4190",name:"Change in Inventory — Work in Progress (Purchases)",accountType:"Resultat - driftskostnad"},
  {code:"4200",name:"Purchases — Finished Self-produced Goods",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4260",name:"Freight, Customs & Forwarding — Finished Goods",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4270",name:"Purchase Price Reduction — Finished Goods",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4290",name:"Change in Inventory — Finished Goods (Purchases)",accountType:"Resultat - driftskostnad"},
  {code:"4301",name:"Purchases — Goods for Resale, VAT-free",defaultVatCode:"11",defaultVatPct:15,accountType:"Resultat - driftskostnad"},
  {code:"4302",name:"Waste Disposal",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4350",name:"Shrinkage & Losses",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4370",name:"Purchase Price Reduction — Resale Goods",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4380",name:"Basis — Import VAT",accountType:"Resultat - driftskostnad"},
  {code:"4390",name:"Change in Inventory — Goods for Resale (Purchases)",accountType:"Resultat - driftskostnad"},
  {code:"4501",name:"Subcontractors, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"4520",name:"Subcontractors — Reportable",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"4590",name:"Change in Inventory — Subcontracted Work",accountType:"Resultat - driftskostnad"},
  {code:"4900",name:"Other Accrual (COGS)",accountType:"Resultat - driftskostnad"},
  {code:"4990",name:"Change in Inventory — Self-produced Fixed Assets",accountType:"Resultat - driftskostnad"},
  {code:"5001",name:"Salary Excl. Holiday Pay Basis",accountType:"Resultat - driftskostnad"},
  {code:"5090",name:"Accrued, Not Paid Salary",accountType:"Resultat - driftskostnad"},
  {code:"5091",name:"Accrued Holiday Pay on Unpaid Salary",accountType:"Resultat - driftskostnad"},
  {code:"5095",name:"Salary Accrual",accountType:"Resultat - driftskostnad"},
  {code:"5096",name:"Holiday Pay Accrual",accountType:"Resultat - driftskostnad"},
  {code:"5099",name:"Other Salary Accruals",accountType:"Resultat - driftskostnad"},
  {code:"5240",name:"Interest Rate Benefit (Employee Loan)",accountType:"Resultat - driftskostnad"},
  {code:"5280",name:"Other Employment Benefit",accountType:"Resultat - driftskostnad"},
  {code:"5285",name:"Other Employment Benefit (Not Subject to Employer's Tax)",accountType:"Resultat - driftskostnad"},
  {code:"5310",name:"Group Life Insurance",accountType:"Resultat - driftskostnad"},
  {code:"5320",name:"Other Reportable Personnel Insurance",accountType:"Resultat - driftskostnad"},
  {code:"5390",name:"Other Reportable Compensation",accountType:"Resultat - driftskostnad"},
  {code:"5401",name:"Employer's Tax on Accrued Holiday Pay",accountType:"Resultat - driftskostnad"},
  {code:"5420",name:"Reportable Pension Cost",accountType:"Resultat - driftskostnad"},
  {code:"5430",name:"Financial Activity Tax on Salary",accountType:"Resultat - driftskostnad"},
  {code:"5431",name:"Financial Activity Tax on Accrued Holiday Pay",accountType:"Resultat - driftskostnad"},
  {code:"5495",name:"Employer's Tax Accrual",accountType:"Resultat - driftskostnad"},
  {code:"5496",name:"Employer's Tax Accrual — Holiday Pay",accountType:"Resultat - driftskostnad"},
  {code:"5500",name:"Other Expense Reimbursement (Employee)",accountType:"Resultat - driftskostnad"},
  {code:"5510",name:"Taxable Portion of Travel Reimbursement",accountType:"Resultat - driftskostnad"},
  {code:"5600",name:"Partner Compensation (ANS etc.)",accountType:"Resultat - driftskostnad"},
  {code:"5700",name:"Apprentice Subsidy",accountType:"Resultat - driftskostnad"},
  {code:"5720",name:"Other Wage Subsidy",accountType:"Resultat - driftskostnad"},
  {code:"5830",name:"Labour Market Measures Reimbursement",accountType:"Resultat - driftskostnad"},
  {code:"5890",name:"Other Reimbursement",accountType:"Resultat - driftskostnad"},
  {code:"5901",name:"Gifts to Employees (Non-deductible)",accountType:"Resultat - driftskostnad"},
  {code:"5912",name:"Overtime Meals",accountType:"Resultat - driftskostnad"},
  {code:"5919",name:"Canteen Cost Deduction — Employees",accountType:"Resultat - driftskostnad"},
  {code:"5920",name:"Occupational Injury Insurance",accountType:"Resultat - driftskostnad"},
  {code:"5930",name:"Other Insurance (Not Subject to Employer's Tax)",accountType:"Resultat - driftskostnad"},
  {code:"5941",name:"LO/NHO — Unemployment & Severance Fund",accountType:"Resultat - driftskostnad"},
  {code:"5942",name:"LO/NHO — Early Retirement (AFP)",accountType:"Resultat - driftskostnad"},
  {code:"5945",name:"Employee Pension Insurance",accountType:"Resultat - driftskostnad"},
  {code:"5970",name:"Reportable Leisure Insurance",accountType:"Resultat - driftskostnad"},
  {code:"5990",name:"Other Personnel Cost",accountType:"Resultat - driftskostnad"},
  {code:"6015",name:"Depreciation — Machinery",accountType:"Resultat - driftskostnad"},
  {code:"6017",name:"Depreciation — Furniture & Fixtures",accountType:"Resultat - driftskostnad"},
  {code:"6050",name:"Impairment — Fixed & Intangible Assets",accountType:"Resultat - driftskostnad"},
  {code:"6190",name:"Other Freight & Transport Cost on Sales",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6210",name:"Gas",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6220",name:"Fuel Oil",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6230",name:"Coal & Coke",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6240",name:"Firewood",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6301",name:"Rent — Premises, VAT-free",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6410",name:"Lease — Furniture & Fixtures",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6421",name:"Lease — IT Systems, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"6422",name:"Lease — IT Systems, Abroad",accountType:"Resultat - driftskostnad"},
  {code:"6430",name:"Lease — Other Office Machines",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6440",name:"Lease — Transport Equipment",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6441",name:"Lease — Transport Equipment, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"6500",name:"Power Tools",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6520",name:"Auxiliary Tools",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6530",name:"Special Tools",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6541",name:"Furniture & Fixtures, VAT-free",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6551",name:"Computer Hardware",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6552",name:"Computer Software",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6553",name:"Computer Hardware, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"6571",name:"Workwear — No VAT Deduction",accountType:"Resultat - driftskostnad"},
  {code:"6591",name:"Other Operating Materials, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"6701",name:"Audit Fee",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6702",name:"Audit Advisory Fee",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6725",name:"Legal Assistance Fee (Deductible)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6726",name:"Legal Assistance Fee (Non-deductible)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6790",name:"Other Purchased Services",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6791",name:"Other Purchased Services, VAT-free",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"6861",name:"Meetings, Courses & Training, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"6901",name:"Telephone, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"6910",name:"Mobile Phone",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7021",name:"Maintenance — Company Car",accountType:"Resultat - driftskostnad"},
  {code:"7050",name:"Logbook / Mileage App License",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7080",name:"Vehicle Costs — Private Car Used for Business",accountType:"Resultat - driftskostnad"},
  {code:"7091",name:"Other Vehicle Cost, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"7092",name:"Traffic Insurance Levy",accountType:"Resultat - driftskostnad"},
  {code:"7142",name:"Non-reportable Travel Cost — 25% VAT",accountType:"Resultat - driftskostnad"},
  {code:"7144",name:"Parking, VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"7148",name:"Road Tolls",accountType:"Resultat - driftskostnad"},
  {code:"7560",name:"Service Cost",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7630",name:"Inspection, Testing & Stamping Fee",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7730",name:"Cost — Treasury Shares",accountType:"Resultat - driftskostnad"},
  {code:"7750",name:"Property & Site Lease Fee",accountType:"Resultat - driftskostnad"},
  {code:"7790",name:"Other Cost (Deductible)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7791",name:"Other Cost (Non-deductible)",accountType:"Resultat - driftskostnad"},
  {code:"7793",name:"Other Cost (Deductible), VAT-free",accountType:"Resultat - driftskostnad"},
  {code:"7805",name:"Sale of Fixed Assets, VAT-free (Alt.)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7807",name:"Sale of Fixed Assets, Outside VAT Scope (Alt.)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7809",name:"Contra — Book Value of Fixed Assets Sold (Alt.)",defaultVatCode:"1",defaultVatPct:25,accountType:"Resultat - driftskostnad"},
  {code:"7831",name:"Change in Provision for Bad Debts",accountType:"Resultat - driftskostnad"},
  {code:"7860",name:"Loss on Contracts",accountType:"Resultat - driftskostnad"},
  {code:"8071",name:"Dividend Income (Shares)",accountType:"Resultat - kapitalinntekt"},
  {code:"8078",name:"Gain on Realization of Shares",accountType:"Resultat - kapitalinntekt"},
  {code:"8080",name:"Value Increase — Financial Instruments at Fair Value",accountType:"Resultat - kapitalinntekt"},
  {code:"8090",name:"Income from Other Investments",accountType:"Resultat - kapitalinntekt"},
  {code:"8130",name:"Interest Expense — Group Companies",accountType:"Resultat - kapitalkostnad"},
  {code:"8140",name:"Interest Expense (Non-deductible)",accountType:"Resultat - kapitalkostnad"},
  {code:"8170",name:"Other Financial Expense",accountType:"Resultat - kapitalkostnad"},
  {code:"8178",name:"Loss on Realization of Shares",accountType:"Resultat - kapitalkostnad"},
  {code:"8310",name:"Tax Refund (Tax Act §16-50) — Financial",accountType:"Resultat - skattekostnad på ordinært resultat"},
  {code:"8410",name:"Extraordinary Gain on Sale of Fixed Assets",accountType:"Resultat - ekstraordinær inntekt"},
  {code:"8450",name:"Extraordinary Public Grants",accountType:"Resultat - ekstraordinær inntekt"},
  {code:"8490",name:"Other Extraordinary Income",accountType:"Resultat - ekstraordinær inntekt"},
  {code:"8510",name:"Extraordinary Loss on Sale of Fixed Assets",accountType:"Resultat - ekstraordinær kostnad"},
  {code:"8590",name:"Other Extraordinary Cost",accountType:"Resultat - ekstraordinær kostnad"},
  {code:"8600",name:"Tax Payable",accountType:"Resultat - skattekostnad på ekstraordinært resultat"},
  {code:"8610",name:"Tax Refund (Tax Act §16-50) — Payable Tax",accountType:"Resultat - skattekostnad på ekstraordinært resultat"},
  {code:"8620",name:"Change in Deferred Tax/Tax Asset",accountType:"Resultat - skattekostnad på ekstraordinært resultat"},
  {code:"8900",name:"Transfers to/from Reserves",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8910",name:"Transfers — Cooperative Joint Capital",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8920",name:"Proposed Dividend",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8930",name:"Group Contribution Received",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8935",name:"Group Contribution Provided",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8940",name:"Shareholder Contribution Received",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8945",name:"Shareholder Contribution Provided",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8950",name:"Bonus Share Issue",accountType:"Resultat - overføringer og disponeringer"},
  {code:"8969",name:"Allocated to Cover Prior Year Loss",accountType:"Resultat - overføringer og disponeringer"},
  {code:"9999",name:"Suspense Account",accountType:"Balanse - eiendeler"},
].map(a=>({...a,matchable:a.code==="1500"||a.code==="2400"}));

export { DEFAULT_ACCOUNTS };
