const DEFAULT_ACCOUNTS=[
  // ── 1000s ASSETS ──────────────────────────────────────────────
  // Fixed Assets (1000–1099)
  {code:"1000",name:"Fixed Assets"},
  {code:"1010",name:"Land & Buildings"},
  {code:"1020",name:"Office Buildings"},
  {code:"1030",name:"Other Real Estate"},
  {code:"1080",name:"Goodwill"},
  // Intangible Assets (1100–1199)
  {code:"1100",name:"Intangible Assets"},
  {code:"1110",name:"Research & Development"},
  {code:"1120",name:"Patents & Licenses"},
  {code:"1130",name:"Goodwill"},
  {code:"1190",name:"Other Fixed Assets"},
  // Machinery & Equipment (1200–1399)
  {code:"1200",name:"Machinery & Plant"},
  {code:"1210",name:"Production Equipment"},
  {code:"1220",name:"Furniture & Fixtures"},
  {code:"1230",name:"Office Equipment"},
  {code:"1240",name:"Computer Equipment"},
  {code:"1249",name:"Other Transport Equipment"},
  {code:"1250",name:"Fixtures & Tools"},
  {code:"1260",name:"Vehicles"},
  {code:"1270",name:"Tools"},
  {code:"1280",name:"Office Machines"},
  {code:"1290",name:"Other Operating Equipment"},
  // Inventory & Stock (1400–1499)
  {code:"1400",name:"Inventory — Raw Materials"},
  {code:"1410",name:"Inventory — Work in Progress"},
  {code:"1420",name:"Inventory — Finished Goods"},
  {code:"1460",name:"Inventory — Goods for Resale"},
  {code:"1480",name:"Prepayments to Suppliers"},
  // Accounts Receivable (1500–1599)
  {code:"1500",name:"Accounts Receivable"},
  {code:"1509",name:"Accounts Receivable — Not on Subledger"},
  {code:"1510",name:"Trade Receivables"},
  {code:"1520",name:"Receivables from Group Companies"},
  {code:"1530",name:"Other Short-term Receivables"},
  {code:"1570",name:"Travel Advances"},
  {code:"1571",name:"Salary Advances"},
  {code:"1579",name:"Other Short-term Receivables (Misc.)"},
  {code:"1580",name:"Provision for Bad Debts"},
  // Other Short-term Receivables (1600–1799)
  {code:"1600",name:"VAT Receivable"},
  {code:"1630",name:"Prepaid Expenses"},
  {code:"1700",name:"Short-term Investments"},
  {code:"1710",name:"Shares in Listed Companies"},
  {code:"1749",name:"Other Prepaid Expenses"},
  {code:"1750",name:"Accrued Rental Income"},
  {code:"1790",name:"Accrued Income (Other)"},
  {code:"1800",name:"Accrued Income"},
  // Bank & Cash (1900–1999)
  {code:"1900",name:"Cash in Hand"},
  {code:"1910",name:"Bank Account — Main"},
  {code:"1920",name:"Bank Account — Operations"},
  {code:"1940",name:"Bank Account — Foreign"},
  {code:"1950",name:"Petty Cash"},
  {code:"1951",name:"Bank Account — Withholding Tax"},
  // ── 2000s EQUITY & LIABILITIES ────────────────────────────────
  // Equity (2000–2099)
  {code:"2000",name:"Share Capital"},
  {code:"2020",name:"Share Premium Reserve"},
  {code:"2050",name:"Retained Earnings"},
  {code:"2055",name:"Owner's Cash Contribution"},
  {code:"2060",name:"Owner's Drawings"},
  {code:"2070",name:"Taxes (Equity)"},
  {code:"2080",name:"Profit / Loss This Year"},
  // Long-term Debt (2100–2299)
  {code:"2100",name:"Long-term Bank Loans"},
  {code:"2110",name:"Mortgage Loans"},
  {code:"2130",name:"Loans from Shareholders"},
  {code:"2200",name:"Deferred Tax Liability"},
  {code:"2220",name:"Debt to Credit Institutions"},
  {code:"2290",name:"Other Provisions"},
  {code:"2299",name:"Other Long-term Debt (Misc.)"},
  // Other Long-term Liabilities (2300–2399)
  {code:"2300",name:"Other Long-term Liabilities"},
  {code:"2310",name:"Loans — Group Companies"},
  {code:"2360",name:"Construction Loan"},
  {code:"2380",name:"Overdraft Facility"},
  {code:"2390",name:"Other Debt to Credit Institutions"},
  // Accounts Payable (2400–2499)
  {code:"2400",name:"Accounts Payable"},
  {code:"2409",name:"Accounts Payable — Not on Subledger"},
  {code:"2410",name:"Trade Payables"},
  {code:"2420",name:"Payables to Group Companies"},
  // VAT & Tax Payable (2500–2599)
  {code:"2500",name:"VAT Payable — Output"},
  {code:"2510",name:"VAT Collected"},
  {code:"2520",name:"VAT — Input (Deductible)"},
  {code:"2540",name:"VAT Payable to Tax Authority"},
  // Public Duties (2600–2699)
  {code:"2600",name:"Withholding Tax Payable"},
  {code:"2610",name:"Social Security Contributions Payable"},
  {code:"2620",name:"Holiday Pay Liability"},
  {code:"2640",name:"Insurance Deductions Payable"},
  {code:"2690",name:"Other Payroll Deductions"},
  // Wages & Salaries Payable (2700–2799) — NOTE: the real Norwegian
  // NS 4102 standard uses this range for output/input VAT settlement
  // sub-accounts (2700 Utgående mva osv.), not payroll. These codes
  // were already in use here for payroll concepts before this
  // comparison, so they're left as-is to avoid breaking any company
  // that's already posted against them — see the VAT settlement
  // accounts added at 2701–2766 below instead, which is where a real
  // Norwegian chart actually expects that detail to live.
  {code:"2700",name:"Salaries Payable"},
  {code:"2701",name:"Output VAT — Services Purchased Abroad"},
  {code:"2702",name:"Output VAT — Medium Rate"},
  {code:"2703",name:"Output VAT — Low Rate"},
  {code:"2710",name:"Pension Contributions Payable"},
  {code:"2711",name:"Input VAT — Services Purchased Abroad"},
  {code:"2712",name:"Input VAT — Medium Rate"},
  {code:"2713",name:"Input VAT — Low Rate"},
  {code:"2720",name:"Employee Deductions Payable"},
  {code:"2727",name:"Output VAT — Goods Imported, High Rate"},
  {code:"2728",name:"Output VAT — Goods Imported, Medium Rate"},
  {code:"2740",name:"VAT Settlement Account"},
  {code:"2741",name:"Input VAT — Goods Imported, High Rate"},
  {code:"2742",name:"Input VAT — Goods Imported, Medium Rate"},
  {code:"2745",name:"Basis — Output VAT, Services Purchased Abroad"},
  {code:"2746",name:"Contra — Basis, Services Purchased Abroad"},
  {code:"2761",name:"Basis — Goods Import, High Rate"},
  {code:"2762",name:"Contra — Basis, Goods Import High Rate"},
  {code:"2763",name:"Basis — Goods Import, Medium Rate"},
  {code:"2764",name:"Contra — Basis, Goods Import Medium Rate"},
  {code:"2765",name:"Basis — Goods Import, VAT-Free"},
  {code:"2766",name:"Contra — Basis, Goods Import VAT-Free"},
  {code:"2770",name:"Employer's Social Security Tax Payable"},
  {code:"2780",name:"Accrued Employer's Tax — Payroll"},
  {code:"2785",name:"Accrued Employer's Tax — Holiday Pay"},
  // Short-term Debt (2800–2899)
  {code:"2800",name:"Short-term Bank Loans"},
  {code:"2810",name:"Credit Facility"},
  // Other Current Liabilities (2900–2999)
  {code:"2900",name:"Accrued Expenses"},
  {code:"2910",name:"Advance Payments from Customers"},
  {code:"2930",name:"Salaries Payable (Unpaid)"},
  {code:"2940",name:"Holiday Pay Payable"},
  {code:"2950",name:"Other Current Liabilities"},
  {code:"2970",name:"Deferred Revenue"},
  {code:"2990",name:"Other Current Liabilities (Misc.)"},
  // ── 3000s REVENUE ─────────────────────────────────────────────
  {code:"3000",name:"Sales Revenue",defaultVatCode:"3"},
  {code:"3010",name:"Sales — Goods",defaultVatCode:"3"},
  {code:"3020",name:"Sales — Services",defaultVatCode:"3"},
  {code:"3030",name:"Sales — Projects",defaultVatCode:"3"},
  {code:"3035",name:"Sales — Goods, Low VAT Rate"},
  {code:"3050",name:"Sales — Services, Low VAT Rate"},
  {code:"3080",name:"Sales Discounts & Allowances"},
  {code:"3100",name:"Sales Revenue — Export",defaultVatCode:"52"},
  {code:"3105",name:"Sales — Goods, Export (VAT-free)"},
  {code:"3120",name:"Sales — Services, Domestic VAT-Free"},
  {code:"3125",name:"Sales — Services, Export (VAT-free)"},
  {code:"3180",name:"Sales Discounts — VAT-Free"},
  {code:"3200",name:"Sales Revenue — VAT Exempt",defaultVatCode:"5"},
  {code:"3220",name:"Sales — Services, Outside VAT Scope"},
  {code:"3280",name:"Sales Discounts — Outside VAT Scope"},
  {code:"3400",name:"Public Grants & Subsidies"},
  {code:"3500",name:"Rental Income"},
  {code:"3600",name:"Commission Income"},
  {code:"3800",name:"Gain on Disposal of Fixed Assets"},
  {code:"3900",name:"Other Operating Income"},
  {code:"3910",name:"Postage Charged to Customers"},
  {code:"3950",name:"Handling Fees — VAT Free"},
  {code:"3960",name:"Gain on Asset Disposal"},
  // ── 4000s COST OF GOODS SOLD ─────────────────────────────────
  {code:"4000",name:"Cost of Goods Sold",defaultVatCode:"1"},
  {code:"4010",name:"Purchases — Raw Materials",defaultVatCode:"1"},
  {code:"4020",name:"Purchases — Goods for Resale",defaultVatCode:"1"},
  {code:"4030",name:"Freight & Import Costs",defaultVatCode:"1"},
  {code:"4060",name:"Freight, Customs & Forwarding — Raw Materials"},
  {code:"4100",name:"Change in Inventory"},
  {code:"4300",name:"Purchases — Goods for Resale, Medium VAT"},
  {code:"4330",name:"Purchases — Goods for Resale, Low VAT"},
  {code:"4360",name:"Freight, Customs & Forwarding — Resale Goods"},
  {code:"4400",name:"Purchases — VAT Free"},
  {code:"4500",name:"Subcontractors",defaultVatCode:"1"},
  {code:"4600",name:"Direct Labour Costs"},
  {code:"4800",name:"Handling Fees — Goods Purchases (VAT)"},
  {code:"4810",name:"Freight & Postage — Goods Purchases (VAT)"},
  {code:"4860",name:"Handling Fees — Goods Purchases (VAT-free)"},
  // ── 5000s PAYROLL & SALARIES ─────────────────────────────────
  {code:"5000",name:"Salaries & Wages"},
  {code:"5010",name:"Salaries — Office Staff"},
  {code:"5020",name:"Salaries — Production Staff"},
  {code:"5030",name:"Temporary / Contract Labour"},
  {code:"5092",name:"Holiday Pay"},
  {code:"5100",name:"Employer Social Security Tax"},
  {code:"5180",name:"Holiday Pay — Accrued"},
  {code:"5182",name:"Employer's Tax on Accrued Holiday Pay"},
  {code:"5192",name:"Holiday Pay — Hourly Staff"},
  {code:"5200",name:"Pension Contributions — Employer"},
  {code:"5210",name:"Benefit — Company Phone"},
  {code:"5220",name:"Benefit — Newspaper Subscription"},
  {code:"5230",name:"Benefit — Board, Lodging & Housing"},
  {code:"5251",name:"Group Life Insurance (Reportable)"},
  {code:"5252",name:"Accident Insurance (Reportable)"},
  {code:"5290",name:"Contra Account — Benefits (Group 52)"},
  {code:"5300",name:"Holiday Pay Expense"},
  {code:"5330",name:"Board & Committee Remuneration"},
  {code:"5395",name:"Other Reportable Compensation (Tax-free)"},
  {code:"5400",name:"Employee Benefits"},
  {code:"5405",name:"Employer's Tax on Accrued Holiday Pay (Alt.)"},
  {code:"5800",name:"Reimbursement — Sick Pay"},
  {code:"5820",name:"Reimbursement — Employer's Social Tax"},
  {code:"5900",name:"Other Personnel Costs"},
  {code:"5910",name:"Canteen Costs"},
  {code:"5950",name:"Mandatory Occupational Pension (OTP)"},
  {code:"5998",name:"Other Personnel Costs (Misc.)"},
  // ── 6000s DEPRECIATION ───────────────────────────────────────
  {code:"6000",name:"Depreciation — Buildings"},
  {code:"6010",name:"Depreciation — Machinery & Equipment"},
  {code:"6020",name:"Depreciation — Vehicles"},
  {code:"6030",name:"Depreciation — IT Equipment"},
  {code:"6040",name:"Depreciation — Intangibles"},
  {code:"6100",name:"Write-down of Assets"},
  {code:"6110",name:"Customs & Forwarding Costs"},
  {code:"6200",name:"Loss on Asset Disposal"},
  {code:"6250",name:"Fuel — Facilities"},
  {code:"6260",name:"Water"},
  {code:"6290",name:"Other Fuel/Heating"},
  {code:"6300",name:"Rent — Premises"},
  {code:"6320",name:"Waste, Water & Drainage"},
  {code:"6340",name:"Light & Heating"},
  {code:"6360",name:"Cleaning"},
  {code:"6390",name:"Other Premises Costs"},
  {code:"6400",name:"Lease — Machinery"},
  {code:"6420",name:"Lease — IT Systems"},
  {code:"6490",name:"Other Lease Costs"},
  {code:"6510",name:"Hand Tools"},
  {code:"6540",name:"Fixtures (Expensed)"},
  {code:"6550",name:"Operating Supplies"},
  {code:"6560",name:"Consumables"},
  {code:"6570",name:"Workwear & Protective Equipment"},
  {code:"6590",name:"Other Operating Supplies"},
  {code:"6600",name:"Repairs & Maintenance — Buildings"},
  {code:"6620",name:"Repairs & Maintenance — Equipment"},
  {code:"6690",name:"Repairs & Maintenance — Other"},
  {code:"6700",name:"Audit & Accounting Fees"},
  {code:"6705",name:"Accounting Fees"},
  {code:"6720",name:"Legal & Financial Advisory Fees"},
  {code:"6780",name:"Central Government Fee"},
  {code:"6781",name:"Central Government Fee — 25% VAT"},
  {code:"6785",name:"Purchase of Services from Abroad"},
  {code:"6800",name:"Office Supplies (Expensed)"},
  {code:"6810",name:"IT Costs"},
  {code:"6820",name:"Printed Materials"},
  {code:"6840",name:"Newspapers, Journals & Books"},
  {code:"6860",name:"Meetings, Courses & Training"},
  {code:"6890",name:"Other Office Costs"},
  {code:"6900",name:"Telephone"},
  {code:"6940",name:"Postage"},
  // ── 7000s OPERATING EXPENSES ─────────────────────────────────
  {code:"7000",name:"Transport & Freight Expenses",defaultVatCode:"1"},
  {code:"7001",name:"EV Charging"},
  {code:"7020",name:"Fuel",defaultVatCode:"1"},
  {code:"7040",name:"Vehicle Running Costs",defaultVatCode:"1"},
  {code:"7090",name:"Other Vehicle Costs"},
  {code:"7095",name:"Tolls"},
  {code:"7098",name:"Parking"},
  // Office & Admin (7100–7199)
  {code:"7100",name:"Office Supplies",defaultVatCode:"1"},
  {code:"7110",name:"Printing & Stationery",defaultVatCode:"1"},
  {code:"7120",name:"Postage & Courier",defaultVatCode:"1"},
  {code:"7130",name:"Cleaning & Caretaking",defaultVatCode:"1"},
  {code:"7140",name:"Electricity & Utilities",defaultVatCode:"1"},
  {code:"7141",name:"Parking (Reportable)"},
  {code:"7150",name:"Rent — Office"},
  {code:"7160",name:"Lease Costs",defaultVatCode:"1"},
  {code:"7180",name:"Waste & Environmental Fees",defaultVatCode:"1"},
  {code:"7190",name:"Other Expense Reimbursements"},
  // Sales & Marketing (7200–7299)
  {code:"7200",name:"Advertising & Marketing",defaultVatCode:"1"},
  {code:"7210",name:"Online Advertising",defaultVatCode:"1"},
  {code:"7220",name:"Trade Fairs & Events",defaultVatCode:"1"},
  {code:"7230",name:"Samples & Promotional Items",defaultVatCode:"1"},
  {code:"7260",name:"Sales Commission",defaultVatCode:"1"},
  // Travel & Entertainment (7300–7399)
  {code:"7300",name:"Travel Expenses",defaultVatCode:"1"},
  {code:"7310",name:"Accommodation",defaultVatCode:"13"},
  {code:"7320",name:"Meals & Entertainment"},
  {code:"7330",name:"Subsistence Allowance"},
  {code:"7350",name:"Representation (Tax-deductible)"},
  {code:"7360",name:"Representation (Non-deductible)"},
  {code:"7390",name:"VAT Rounding"},
  {code:"7395",name:"Rounding (Other)"},
  // IT & Telecom (7400–7499)
  {code:"7400",name:"IT & Software Costs",defaultVatCode:"1"},
  {code:"7410",name:"Phone & Mobile",defaultVatCode:"1"},
  {code:"7420",name:"Internet & Broadband",defaultVatCode:"1"},
  {code:"7430",name:"Cloud & SaaS Subscriptions",defaultVatCode:"1"},
  // Insurance & Fees (7500–7599)
  {code:"7500",name:"Insurance Premiums"},
  {code:"7510",name:"Legal & Professional Fees",defaultVatCode:"1"},
  {code:"7520",name:"Accounting & Audit Fees",defaultVatCode:"1"},
  {code:"7530",name:"Consulting Fees",defaultVatCode:"1"},
  {code:"7540",name:"Membership Fees & Subscriptions"},
  {code:"7550",name:"Public Duties & Licence Fees"},
  // Repairs & Maintenance (7600–7699)
  {code:"7600",name:"Repairs & Maintenance",defaultVatCode:"1"},
  {code:"7610",name:"Maintenance — Buildings",defaultVatCode:"1"},
  {code:"7620",name:"Maintenance — Equipment",defaultVatCode:"1"},
  // Finance & Bank (7700–7799)
  {code:"7700",name:"Bank Charges"},
  {code:"7710",name:"Payment Transaction Fees"},
  {code:"7720",name:"Interest Expense — Short-term"},
  {code:"7740",name:"Rounding — Other"},
  {code:"7770",name:"Bank & Card Fees"},
  {code:"7798",name:"Other Tax-deductible Expenses"},
  // Other Admin (7800–7899)
  {code:"7800",name:"Other Administrative Expenses",defaultVatCode:"1"},
  {code:"7820",name:"Recovery of Previously Written-off Receivables"},
  {code:"7830",name:"Bad Debt Write-off"},
  {code:"7890",name:"Miscellaneous Expenses"},
  // Extraordinary (7900–7999)
  {code:"7900",name:"Extraordinary Expenses"},
  // ── 8000s FINANCE ITEMS ───────────────────────────────────────
  {code:"8000",name:"Interest Income"},
  {code:"8010",name:"Dividend Income"},
  {code:"8020",name:"Gain on Sale of Investments"},
  {code:"8030",name:"Currency Gain"},
  {code:"8040",name:"Interest on Tax Refund (Tax-free)"},
  {code:"8050",name:"Other Interest Income"},
  {code:"8056",name:"Reminder Fee Income"},
  {code:"8060",name:"Currency Gain (Agio)"},
  {code:"8070",name:"Other Financial Income"},
  {code:"8100",name:"Interest Expense — Long-term"},
  {code:"8110",name:"Currency Loss"},
  {code:"8120",name:"Loss on Sale of Investments"},
  {code:"8150",name:"Interest Expense — Credit Institutions"},
  {code:"8160",name:"Currency Loss (Disagio)"},
  {code:"8179",name:"Other Financial Expenses"},
  {code:"8300",name:"Extraordinary Income"},
  {code:"8320",name:"Extraordinary Expense"},
  {code:"8400",name:"Extraordinary Income (Alt.)"},
  {code:"8500",name:"Extraordinary Expense (Alt.)"},
  {code:"8800",name:"Income Tax Expense"},
  {code:"8810",name:"Deferred Tax Expense"},
  {code:"8928",name:"Private Use of Electronic Communication"},
  {code:"8960",name:"Transfers to Other Equity"},
  {code:"8990",name:"Uncovered Loss (Reserve)"},
  // ── 9000s INTERNAL / CLEARING ─────────────────────────────────
  {code:"9000",name:"Internal Settlement Account"},
  {code:"9100",name:"Clearing Account"},
  {code:"9200",name:"Opening Balance Account"},

  // ── ADDED FROM TRIPLETEX'S FULL 572-ACCOUNT REFERENCE ──────────
  // Tripletex's export represents the complete, generic NS 4102
  // standard chart used across ordinary Norwegian firms (vs. Visma's
  // company export, which only listed accounts one specific taxi
  // business had actually activated — narrower and industry-skewed).
  // Company-specific rows (named bank accounts, a specific overdraft
  // facility, a named related-company balance) were excluded; only
  // generic standard codes are added here, as defaults for all firms.
  {code:"1005",name:"Research & Development (Self-developed)"},
  {code:"1025",name:"Concessions (Self-developed)"},
  {code:"1035",name:"Patents (Self-developed)"},
  {code:"1040",name:"Licenses (Acquired)"},
  {code:"1045",name:"Licenses (Self-developed)"},
  {code:"1050",name:"Trademarks (Acquired)"},
  {code:"1055",name:"Trademarks (Self-developed)"},
  {code:"1060",name:"Other Rights (Acquired)"},
  {code:"1065",name:"Other Rights (Self-developed)"},
  {code:"1070",name:"Deferred Tax Asset"},
  {code:"1117",name:"Electrotechnical Equipment (Power Companies)"},
  {code:"1140",name:"Agricultural Property"},
  {code:"1145",name:"Forestry Property"},
  {code:"1150",name:"Plots of Land"},
  {code:"1155",name:"Other Land Areas"},
  {code:"1160",name:"Residential Property incl. Land"},
  {code:"1180",name:"Investment Property"},
  {code:"1224",name:"Rigs"},
  {code:"1225",name:"Aircraft"},
  {code:"1233",name:"Vans"},
  {code:"1235",name:"Accum. Depreciation — Vans (1233)"},
  {code:"1242",name:"Trucks"},
  {code:"1243",name:"Tractors"},
  {code:"1248",name:"Forklifts"},
  {code:"1251",name:"Depreciation on Furniture & Fixtures (1250)"},
  {code:"1252",name:"Accum. Depreciation — Other Transport Equipment (1249)"},
  {code:"1265",name:"Fixed Building Fixtures, Leased Premises"},
  {code:"1281",name:"Accum. Depreciation — Office Machines (1280)"},
  {code:"1291",name:"Other Operating Equipment (Non-depreciable)"},
  {code:"1300",name:"Investments in Subsidiaries"},
  {code:"1310",name:"Investments in Other Group Companies"},
  {code:"1312",name:"Investments in Jointly Controlled Entities"},
  {code:"1330",name:"Investments in Associated Companies"},
  {code:"1340",name:"Loans to Associated & Jointly Controlled Companies"},
  {code:"1350",name:"Investments in Shares & Fund Units"},
  {code:"1360",name:"Bonds"},
  {code:"1370",name:"Receivables from Owners"},
  {code:"1375",name:"Receivables from Board Members"},
  {code:"1380",name:"Receivables from Employees"},
  {code:"1394",name:"Overfunded Pension Obligations"},
  {code:"1395",name:"Tenant Deposits Held"},
  {code:"1396",name:"Deposits"},
  {code:"1397",name:"Prepaid Leasing"},
  {code:"1398",name:"Improvements to Leased Assets"},
  {code:"1399",name:"Other Receivables"},
  {code:"1401",name:"Semi-finished Goods"},
  {code:"1405",name:"Auxiliary Materials"},
  {code:"1408",name:"Operating Materials & Spare Parts"},
  {code:"1409",name:"Change in Inventory — Raw Materials"},
  {code:"1429",name:"Change in Inventory — Work in Progress"},
  {code:"1440",name:"Finished Self-produced Goods"},
  {code:"1449",name:"Change in Inventory — Finished Self-produced Goods"},
  {code:"1465",name:"Demonstration Goods"},
  {code:"1469",name:"Change in Inventory — Goods for Resale"},
  {code:"1490",name:"Biological Assets"},
  {code:"1550",name:"Trade Receivables — Group Companies"},
  {code:"1560",name:"Other Receivables — Group Companies"},
  {code:"1572",name:"Other Short-term Loans to Employees"},
  {code:"1575",name:"Advance — Tax Refund (Tax Act §16-50)"},
  {code:"1576",name:"Short-term Receivables from Owners/Board"},
  {code:"1585",name:"Provision for Losses on Other Receivables"},
  {code:"1590",name:"Other Current Assets"},
  {code:"1601",name:"Output VAT — Medium Rate"},
  {code:"1602",name:"Output VAT — Low Rate"},
  {code:"1603",name:"Output VAT — Services Purchased Abroad"},
  {code:"1610",name:"Input VAT — High Rate"},
  {code:"1611",name:"Input VAT — Medium Rate"},
  {code:"1612",name:"Input VAT — Low Rate"},
  {code:"1613",name:"Input VAT on Imports — High Rate"},
  {code:"1614",name:"Input VAT on Imports — Medium Rate"},
  {code:"1640",name:"VAT Settlement Account"},
  {code:"1650",name:"VAT Compensation — High Rate"},
  {code:"1651",name:"VAT Compensation — Medium Rate"},
  {code:"1652",name:"VAT Compensation — Low Rate"},
  {code:"1654",name:"VAT Compensation Settlement Account"},
  {code:"1655",name:"Basis — VAT Compensation, High Rate"},
  {code:"1656",name:"Basis — VAT Compensation, Medium Rate"},
  {code:"1657",name:"Basis — VAT Compensation, Low Rate"},
  {code:"1659",name:"Contra — Basis, VAT Compensation"},
  {code:"1670",name:"Public Grants Receivable"},
  {code:"1720",name:"Other Deposits"},
  {code:"1740",name:"Prepaid, Not Accrued Salary"},
  {code:"1741",name:"Prepaid Electricity & Heating"},
  {code:"1742",name:"Prepaid Insurance"},
  {code:"1743",name:"Prepaid Leasing (Short-term)"},
  {code:"1760",name:"Accrued Interest Income"},
  {code:"1770",name:"Other Accruals"},
  {code:"1780",name:"Called-up, Unpaid Share Capital"},
  {code:"1810",name:"Market-based Shares & Fund Units"},
  {code:"1820",name:"Other Shares"},
  {code:"1830",name:"Market-based Bonds"},
  {code:"1840",name:"Other Bonds"},
  {code:"1850",name:"Market-based Short-term Bonds (Certificates)"},
  {code:"1860",name:"Other Short-term Bonds (Certificates)"},
  {code:"1870",name:"Other Market-based Financial Instruments"},
  {code:"1880",name:"Other Financial Instruments"},
  {code:"1908",name:"Cash — Foreign Currency"},
  {code:"1909",name:"Cash Differences"},
  {code:"1921",name:"Bank Deposit — Unrestricted"},
  {code:"2010",name:"Treasury Shares"},
  {code:"2025",name:"Unregistered Capital Increase/Decrease"},
  {code:"2030",name:"Other Paid-in Capital"},
  {code:"2041",name:"Fund for Valuation Differences"},
  {code:"2042",name:"Fund for Valuation Differences — Partnership"},
  {code:"2045",name:"Fund for Fair Value Changes — Other Companies"},
  {code:"2051",name:"Non-deductible Representation Costs"},
  {code:"2052",name:"Non-deductible Membership Fees/Gifts"},
  {code:"2053",name:"Other Non-deductible Costs"},
  {code:"2054",name:"Tax-free Income"},
  {code:"2056",name:"Contribution of Other Assets"},
  {code:"2057",name:"Deduction — Private Vehicle Use at Standard Rate"},
  {code:"2058",name:"Other Equity Corrections"},
  {code:"2061",name:"Cash Withdrawals (Owner)"},
  {code:"2063",name:"Withdrawal of Fixed Assets (Owner)"},
  {code:"2064",name:"Withdrawal of Goods & Services (Owner)"},
  {code:"2065",name:"Own Home in Business Property"},
  {code:"2067",name:"Private Light & Heating"},
  {code:"2068",name:"Private Electronic Communication Costs"},
  {code:"2069",name:"Other Private Costs"},
  {code:"2072",name:"Taxes (Owner Drawings)"},
  {code:"2075",name:"Private Use of Business Vehicle"},
  {code:"2077",name:"Own Sickness & Accident Insurance Premium"},
  {code:"2078",name:"Supplementary Sick Pay Insurance Premium"},
  {code:"2099",name:"Transfers — Other Equity"},
  {code:"2120",name:"Deferred Tax"},
  {code:"2160",name:"Unearned Income"},
  {code:"2180",name:"Other Provisions for Liabilities"},
  {code:"2210",name:"Bond Loan"},
  {code:"2240",name:"Mortgage Loan"},
  {code:"2250",name:"Debt to Employees & Owners"},
  {code:"2260",name:"Debt to Group Companies"},
  {code:"2270",name:"Other Foreign Currency Loans"},
  {code:"2280",name:"Silent Partnership & Subordinated Loan Capital"},
  {code:"2320",name:"Bond Loan (Short-term)"},
  {code:"2340",name:"Other Foreign Currency Loans (Short-term)"},
  {code:"2460",name:"Trade Payables — Group Companies"},
  {code:"2530",name:"Tax Refund (Tax Act §16-50)"},
  {code:"2630",name:"Social Security Deduction (Employee)"},
  {code:"2650",name:"Union Dues Withheld"},
  {code:"2670",name:"Low-income Fund Withheld"},
  {code:"2704",name:"Output VAT — Services Purchased Abroad, Low Rate"},
  {code:"2705",name:"Output VAT — Imports, High Rate"},
  {code:"2706",name:"Output VAT — Imports, Medium Rate"},
  {code:"2707",name:"Output VAT — Emission Allowances & Gold"},
  {code:"2714",name:"Input VAT on Imports — Medium Rate (Direct-posted)"},
  {code:"2771",name:"Financial Activity Tax on Salary Payable"},
  {code:"2786",name:"Accrued Financial Activity Tax — Holiday Pay"},
  {code:"2790",name:"Other Public Duties"},
  {code:"2920",name:"Debt to Group Companies (Current)"},
  {code:"2945",name:"Payroll Accrual"},
  {code:"2960",name:"Other Accrued Expenses"},
  {code:"2965",name:"Prepaid Income"},
  {code:"2980",name:"Board Remuneration Accrual"},
  {code:"2981",name:"Audit Fee Accrual"},
  {code:"2982",name:"Accounting Fee Accrual"},
  {code:"2989",name:"Other Liabilities Accrual"},
  // "12" and "6" below were invalid/wrong MVA codes — "12" doesn't exist in
  // MVA_CODES at all (silently produced 0% VAT on any sale posted here
  // instead of erroring), and "6" is "outside VAT scope" (also 0%) when
  // this account is actually a normal 15% output sale. Corrected to the
  // real codes (31 = 15% output, 33 = 12% output) from utils.js MVA_CODES.
  {code:"3001",name:"Sales Revenue, Taxable, Medium Rate",defaultVatCode:"31"},
  {code:"3002",name:"Sales Revenue, Taxable, Low Rate",defaultVatCode:"33"},
  // Raw fish sales use Norway's special 11.11% rate (mva-kode 32), which
  // isn't modeled in this app's MVA_CODES list — left with no default
  // rather than a wrong one; whoever posts here picks the rate manually.
  {code:"3011",name:"Sales Revenue — Raw Fish"},
  {code:"3060",name:"Withdrawal of Goods/Services (Sales)"},
  {code:"3061",name:"Withdrawal of Goods/Services, Medium Rate"},
  {code:"3062",name:"Withdrawal of Goods/Services, Low Rate"},
  {code:"3063",name:"Contra — Withdrawal of Goods/Services"},
  {code:"3090",name:"Accrued, Not Invoiced Income"},
  {code:"3092",name:"Contra — Sales Revenue Fish, Taxable, Medium Rate"},
  {code:"3093",name:"Contra — Sales Revenue, Taxable, Low Rate"},
  {code:"3094",name:"Contra — Sales Revenue, Taxable, Medium Rate"},
  {code:"3095",name:"Contra — Sales Revenue, Taxable, High Rate"},
  {code:"3107",name:"Sales Revenue — Export of Goods/Services (VAT-free)"},
  {code:"3108",name:"Sales Revenue — Gold & Emission Allowances (VAT-free)"},
  {code:"3160",name:"Withdrawal of Goods/Services (VAT-free)"},
  {code:"3190",name:"Accrued, Not Invoiced Income (VAT-free)"},
  {code:"3195",name:"Contra — Sales Revenue, VAT-free"},
  {code:"3197",name:"Contra — Sales Revenue, Export (VAT-exempt)"},
  {code:"3198",name:"Contra — Sales Revenue, Gold/Allowances (Reverse Charge)"},
  {code:"3260",name:"Withdrawal of Goods/Services (Outside VAT Scope)"},
  {code:"3290",name:"Accrued, Not Invoiced Income (Outside VAT Scope)"},
  {code:"3295",name:"Contra — Sales Revenue, Outside VAT Scope"},
  {code:"3300",name:"Special Public Levy — Goods Produced/Sold"},
  {code:"3440",name:"Special Public Grant — Services"},
  {code:"3605",name:"Rental Income — Real Estate, Outside VAT Scope"},
  {code:"3610",name:"Rental Income — Other Fixed Assets, Taxable"},
  {code:"3615",name:"Rental Income — Other Fixed Assets, VAT-free"},
  {code:"3620",name:"Other Rental Income"},
  {code:"3690",name:"Accrued, Not Invoiced Rental Income"},
  {code:"3700",name:"Commission Income, Taxable"},
  {code:"3705",name:"Commission Income, VAT-free"},
  {code:"3710",name:"Commission Income, Outside VAT Scope"},
  {code:"3790",name:"Accrued, Not Invoiced Commission"},
  {code:"3805",name:"Sale of Fixed Assets, VAT-free"},
  {code:"3806",name:"Sale of Fixed Assets, VAT-free — Additional Posting"},
  {code:"3807",name:"Sale of Fixed Assets, Outside VAT Scope"},
  {code:"3809",name:"Contra — Book Value of Fixed Assets Sold"},
  {code:"3850",name:"Value Changes — Investment Property"},
  {code:"3870",name:"Value Changes — Biological Assets"},
  {code:"4070",name:"Purchase Price Reduction — Raw Materials"},
  {code:"4090",name:"Change in Inventory — Raw Materials (Purchases)"},
  {code:"4160",name:"Freight, Customs & Forwarding — Raw Materials (Alt.)"},
  {code:"4170",name:"Purchase Price Reduction — Work in Progress"},
  {code:"4190",name:"Change in Inventory — Work in Progress (Purchases)"},
  {code:"4200",name:"Purchases — Finished Self-produced Goods"},
  {code:"4260",name:"Freight, Customs & Forwarding — Finished Goods"},
  {code:"4270",name:"Purchase Price Reduction — Finished Goods"},
  {code:"4290",name:"Change in Inventory — Finished Goods (Purchases)"},
  {code:"4301",name:"Purchases — Goods for Resale, VAT-free"},
  {code:"4302",name:"Waste Disposal"},
  {code:"4350",name:"Shrinkage & Losses"},
  {code:"4370",name:"Purchase Price Reduction — Resale Goods"},
  {code:"4380",name:"Basis — Import VAT"},
  {code:"4390",name:"Change in Inventory — Goods for Resale (Purchases)"},
  {code:"4501",name:"Subcontractors, VAT-free"},
  {code:"4520",name:"Subcontractors — Reportable"},
  {code:"4590",name:"Change in Inventory — Subcontracted Work"},
  {code:"4900",name:"Other Accrual (COGS)"},
  {code:"4990",name:"Change in Inventory — Self-produced Fixed Assets"},
  {code:"5001",name:"Salary Excl. Holiday Pay Basis"},
  {code:"5090",name:"Accrued, Not Paid Salary"},
  {code:"5091",name:"Accrued Holiday Pay on Unpaid Salary"},
  {code:"5095",name:"Salary Accrual"},
  {code:"5096",name:"Holiday Pay Accrual"},
  {code:"5099",name:"Other Salary Accruals"},
  {code:"5240",name:"Interest Rate Benefit (Employee Loan)"},
  {code:"5280",name:"Other Employment Benefit"},
  {code:"5285",name:"Other Employment Benefit (Not Subject to Employer's Tax)"},
  {code:"5310",name:"Group Life Insurance"},
  {code:"5320",name:"Other Reportable Personnel Insurance"},
  {code:"5390",name:"Other Reportable Compensation"},
  {code:"5401",name:"Employer's Tax on Accrued Holiday Pay"},
  {code:"5420",name:"Reportable Pension Cost"},
  {code:"5430",name:"Financial Activity Tax on Salary"},
  {code:"5431",name:"Financial Activity Tax on Accrued Holiday Pay"},
  {code:"5495",name:"Employer's Tax Accrual"},
  {code:"5496",name:"Employer's Tax Accrual — Holiday Pay"},
  {code:"5500",name:"Other Expense Reimbursement (Employee)"},
  {code:"5510",name:"Taxable Portion of Travel Reimbursement"},
  {code:"5600",name:"Partner Compensation (ANS etc.)"},
  {code:"5700",name:"Apprentice Subsidy"},
  {code:"5720",name:"Other Wage Subsidy"},
  {code:"5830",name:"Labour Market Measures Reimbursement"},
  {code:"5890",name:"Other Reimbursement"},
  {code:"5901",name:"Gifts to Employees (Non-deductible)"},
  {code:"5912",name:"Overtime Meals"},
  {code:"5919",name:"Canteen Cost Deduction — Employees"},
  {code:"5920",name:"Occupational Injury Insurance"},
  {code:"5930",name:"Other Insurance (Not Subject to Employer's Tax)"},
  {code:"5941",name:"LO/NHO — Unemployment & Severance Fund"},
  {code:"5942",name:"LO/NHO — Early Retirement (AFP)"},
  {code:"5945",name:"Employee Pension Insurance"},
  {code:"5970",name:"Reportable Leisure Insurance"},
  {code:"5990",name:"Other Personnel Cost"},
  {code:"6015",name:"Depreciation — Machinery"},
  {code:"6017",name:"Depreciation — Furniture & Fixtures"},
  {code:"6050",name:"Impairment — Fixed & Intangible Assets"},
  {code:"6190",name:"Other Freight & Transport Cost on Sales"},
  {code:"6210",name:"Gas"},
  {code:"6220",name:"Fuel Oil"},
  {code:"6230",name:"Coal & Coke"},
  {code:"6240",name:"Firewood"},
  {code:"6301",name:"Rent — Premises, VAT-free"},
  {code:"6410",name:"Lease — Furniture & Fixtures"},
  {code:"6421",name:"Lease — IT Systems, VAT-free"},
  {code:"6422",name:"Lease — IT Systems, Abroad"},
  {code:"6430",name:"Lease — Other Office Machines"},
  {code:"6440",name:"Lease — Transport Equipment"},
  {code:"6441",name:"Lease — Transport Equipment, VAT-free"},
  {code:"6500",name:"Power Tools"},
  {code:"6520",name:"Auxiliary Tools"},
  {code:"6530",name:"Special Tools"},
  {code:"6541",name:"Furniture & Fixtures, VAT-free"},
  {code:"6551",name:"Computer Hardware"},
  {code:"6552",name:"Computer Software"},
  {code:"6553",name:"Computer Hardware, VAT-free"},
  {code:"6571",name:"Workwear — No VAT Deduction"},
  {code:"6591",name:"Other Operating Materials, VAT-free"},
  {code:"6701",name:"Audit Fee"},
  {code:"6702",name:"Audit Advisory Fee"},
  {code:"6725",name:"Legal Assistance Fee (Deductible)"},
  {code:"6726",name:"Legal Assistance Fee (Non-deductible)"},
  {code:"6790",name:"Other Purchased Services"},
  {code:"6791",name:"Other Purchased Services, VAT-free"},
  {code:"6861",name:"Meetings, Courses & Training, VAT-free"},
  {code:"6901",name:"Telephone, VAT-free"},
  {code:"6910",name:"Mobile Phone"},
  {code:"7021",name:"Maintenance — Company Car"},
  {code:"7050",name:"Logbook / Mileage App License"},
  {code:"7080",name:"Vehicle Costs — Private Car Used for Business"},
  {code:"7091",name:"Other Vehicle Cost, VAT-free"},
  {code:"7092",name:"Traffic Insurance Levy"},
  {code:"7142",name:"Non-reportable Travel Cost — 25% VAT"},
  {code:"7144",name:"Parking, VAT-free"},
  {code:"7148",name:"Road Tolls"},
  {code:"7560",name:"Service Cost"},
  {code:"7630",name:"Inspection, Testing & Stamping Fee"},
  {code:"7730",name:"Cost — Treasury Shares"},
  {code:"7750",name:"Property & Site Lease Fee"},
  {code:"7790",name:"Other Cost (Deductible)"},
  {code:"7791",name:"Other Cost (Non-deductible)"},
  {code:"7793",name:"Other Cost (Deductible), VAT-free"},
  {code:"7805",name:"Sale of Fixed Assets, VAT-free (Alt.)"},
  {code:"7807",name:"Sale of Fixed Assets, Outside VAT Scope (Alt.)"},
  {code:"7809",name:"Contra — Book Value of Fixed Assets Sold (Alt.)"},
  {code:"7831",name:"Change in Provision for Bad Debts"},
  {code:"7860",name:"Loss on Contracts"},
  {code:"8071",name:"Dividend Income (Shares)"},
  {code:"8078",name:"Gain on Realization of Shares"},
  {code:"8080",name:"Value Increase — Financial Instruments at Fair Value"},
  {code:"8090",name:"Income from Other Investments"},
  {code:"8130",name:"Interest Expense — Group Companies"},
  {code:"8140",name:"Interest Expense (Non-deductible)"},
  {code:"8170",name:"Other Financial Expense"},
  {code:"8178",name:"Loss on Realization of Shares"},
  {code:"8310",name:"Tax Refund (Tax Act §16-50) — Financial"},
  {code:"8410",name:"Extraordinary Gain on Sale of Fixed Assets"},
  {code:"8450",name:"Extraordinary Public Grants"},
  {code:"8490",name:"Other Extraordinary Income"},
  {code:"8510",name:"Extraordinary Loss on Sale of Fixed Assets"},
  {code:"8590",name:"Other Extraordinary Cost"},
  {code:"8600",name:"Tax Payable"},
  {code:"8610",name:"Tax Refund (Tax Act §16-50) — Payable Tax"},
  {code:"8620",name:"Change in Deferred Tax/Tax Asset"},
  {code:"8900",name:"Transfers to/from Reserves"},
  {code:"8910",name:"Transfers — Cooperative Joint Capital"},
  {code:"8920",name:"Proposed Dividend"},
  {code:"8930",name:"Group Contribution Received"},
  {code:"8935",name:"Group Contribution Provided"},
  {code:"8940",name:"Shareholder Contribution Received"},
  {code:"8945",name:"Shareholder Contribution Provided"},
  {code:"8950",name:"Bonus Share Issue"},
  {code:"8969",name:"Allocated to Cover Prior Year Loss"},
  {code:"9999",name:"Suspense Account"},
].map(a=>({...a,matchable:a.code==="1500"||a.code==="2400"}));

export { DEFAULT_ACCOUNTS };
